# 左側：系統資源
- resources:
    label: Debian Monitor
    cpu: true
    memory: true
    disk: /
    refresh: 3000
# 右側：日期時間
- datetime:
    text_size: xl
    format:
      timeStyle: short
      dateStyle: short
      hourCycle: h23

# 右側：搜尋框
- search:
    provider: google
    target: _blank

