_top.defLang = {
lang_login: {
  lblUserName:"用户名:",
  lblPassword:"密码:",
  btnLogin:"登陆",
  tipLogin:"登陆",
  lblsaveUser:"记住账号",
  lblsavePass:"记住密码",
  errLoginUserInvalid:"用户名或密码无效.请再试一次.",
  errLoginSessionNum:"登录失败,因为登录的用户太多.",
  titConfirmLogout:"确认注销",
  msgConfirmLogout:"注销将断开您当前的会话.如果系统重新启动,配置中未保存的更改将丢失.",
  msgLogout:"您已退出交换机.",
  msgSessionTimeout:"会话已超时。您可以重新登录.",
  sirivision_1 :"Copyright &copy; 2001 - 2021 深圳市三旺通信股份有限公司"
},

<!--#ifdef CONFIG_SYS_AAA-->
/* AAA */
lang_aaa: {
 titLoginLists:"方法列表表",
   lblListName:"名称",
   lblMethodList:"序列",
   errDfltListDel:"默认列表无法删除",
   lblMethodEmpty:"空",
   lblMethodNone:"无",
   lblMethodLocal:"本地",
   lblMethodEnable:"启用",
   lblMethodRadius:"RADIUS",
   lblMethodTacplus:"TACACS +",

   titAddLoginList:"添加方法列表",
   titEditLoginList:"编辑方法列表",
   lblMethod:"方法$ 1"
},
<!--#endif-->

<!--#ifdef CONFIG_SYS_USER_DEFINED_ACL-->
/* ACL */
lang_acl: {
  titAclTable:"ACL表",
  titAceTable:"ACE表",
  titAclACEAdd:"添加ACE",
  titAclACEEdit:"编辑ACE",
  titAclBindingTable:"ACL绑定表",
  titAclBindingAdd:"添加ACL绑定",
  titAclBindingEdit:"编辑ACL绑定",
  msgAclBindingPorts:"注意：将ACL绑定到端口后，无法编辑规则",
  msgAclEmptyACL:"注意：没有任何规则的ACL不能绑定",

  lblAclName:"ACL名称",
  lblAclAceCnts:"规则",
  lblAclBindingPorts:"端口",
  lblAclSequence:"序列",
  lblAclAction:"动作",
  lblAclPermit:"许可证",
  lblAclDeny:"拒绝",
  lblAclShutdown:"关机",
  lblAclSource:"源",
  lblAclDestination:"目标",
  lblAclMac:"MAC ACL",
  lblAclIp:"IP",
  lblAclIpv4:"IPv4 ACL",
  lblAclIpv6:"IPv6 ACL",
  lblAclPort:"端口",
  lblAclAddress:"地址",
  lblAclMask:"遮罩",
  lblAclPrefix:"前缀",
  lblAcl8021p:"802.1p",
  lblAclValue:"值",
  lblAclEth:"以太网类型",
  lblAclProto:"协议",
  lblAclSingle:"单一",
  lblAclRange:"范围",
  lblAclTcpFlag:"TCP标志",
  lblAclSet:"设置",
  lblAclUnset:"取消",
  lblAclNone:"无关",
  lblAclToS:"服务类型",
  lblAclDSCP:"DSCP",
  lblAclIPP:"IP优先级",
  lblAclTcpFlag:"TCP标志",
  lblAclICMP:"ICMP",
  lblAclType:"类型",
  lblAclCode:"代码",
  lblAclAny:"任何",
  lblAclSelctList:"选择",
  lblAclIpputValue:"定义",
  lblAclRateLimit:"速率限制",
  errPortRange:"结束端口不能小于或等于开始端口"
},
<!--#endif-->

<!--#ifdef CONFIG_SYS_MGMT_ACL-->
/* ACL - Manageement*/
lang_acl_mgmt: {
   titMgmtACLTable:"管理ACL表",
   titMgmtACETable:"管理ACE表",
   titMgmtACEAdd:"TACACS+",
   titMgmtACEEdit:"添加Managemet ACE",
   lblMgmtACLName:"ACL名称",
   lblMgmtACENUM:"规则",
   lblMgmtACLActive:"状态",
   lblMgmtACLPri:"优先级",
   lblMgmtACLAction:"动作",
   lblMgmtACLService:"服务",
   lblMgmtACLSrcIp:"地址 / 掩码",
   lblMgmtACLPermit:"许可证",
   lblMgmtACLDeny:"拒绝",
   lblMgmtACLAll:"全部",
   lblMgmtACLHTTP:"Http",
   lblMgmtACLHTTPS:"Https",
   lblMgmtACLSNMP:"Snmp",
   lblMgmtACLSSH:"SSH",
   lblMgmtACLTelnet:"Telnet"
},
<!--#endif-->

<!--#ifdef CONFIG_SYS_PROTO_AUTHMGR-->
lang_authmgr: {
  lblAuthType:"身份验证类型",
  lblDot1x:"802.1x",
  lblMac:"基于MAC",
  lblWeb:"基于WEB",
  lblGuestVlan:"访客VLAN",
  lblMacRadiusUser:"基于MAC的用户ID格式",

  titAuthmgrPortModeTable:"端口模式表",
  titAuthmgrEditPortMode:"编辑端口模式",
  titAuthmgrPortSettingTable:"端口设置表",
  titAuthmgrEditPortSetting:"编辑端口设置",

  lblPortCtrl:"端口控制",
  lblPortCtrlDisabled:"已禁用",
  lblPortCtrlAuto:"自动",
  lblPortCtrlForceAuth:"强制授权",
  lblPortCtrlForceUnauth:"强制未经授权",
  lblHostMode:"主机模式",
  lblHostModeMultiAuth:"多重身份验证",
  lblHostModeMultiHost:"多个主机",
  lblHostModeSingleHost:"单个主机",
  lblOrder:"订单",
  lblAvailType:"可用类型",
  lblSelType:"选择类型",
  lblMethod:"方法",
  lblAvailMethod:"可用方法",
  lblSelMethod:"选择方法",
  lblMethodRadius:"RADIUS",
  lblMethodLocal:"本地",
  lblReauth:"重新认证",
  lblMaxHost:"最大主机数",
  lblVlanAssign:"VLAN分配模式",
  lblVlanAssignDisable:"禁用",
  lblVlanAssignReject:"拒绝",
  lblVlanAssignStatic:"静态",
  lblCommonTimer:"通用计时器",
  lblTimerReauth:"重新认证",
  lblTimerInact:"无效",
  lblTimerQuiet:"安静",
  lblDot1xParam:"802.1x参数",
  lblMaxReq:"最大请求数",
  lblTxPeriod:"发送周期",
  lblSuppTimeout:"请求方超时",
  lblSrvTimeout:"服务器超时",
  lblWebParam:"基于Web的参数",
  lblLoginAttempt:"最大登录数",
  lblInfinite:"无限",

  errTypeOrderEmpty:"必须为身份验证顺序选择至少一种类型",
  errTypeOrderWebNotLast:"基于Web的类型必须是身份验证顺序的最后一个",
  errMethodEmpty:"必须选择至少一种身份验证方法",

  titMacLocalAcctTable:"基于MAC的本地帐户表",
  titAddMacLocalAcct:"添加基于MAC的本地帐户",
  titEditMacLocalAcct:"编辑基于MAC的本地帐户",
  titWebLocalAcctTable:"基于WEB的本地帐户表",
  titAddWebLocalAcct:"添加基于Web的本地帐户",
  titEditWebLocalAcct:"编辑基于WEB的本地帐户",
  lblAssignTimer:"分配的计时器",
  lblCtrl:"控件",
  lblTimeoutSec:"超时（秒）",
  lblMacAddr:"MAC地址",
  lblAssignVlan:"VLAN",

  lblUserName:"用户名",
  lblPwd:"密码",
  lblPwdConfirm:"确认密码",

  titSessTable:"会话表",
  lblCurrType:"当前类型",
  lblStatus:"状态",
  lblStsRunning:"正在运行",
  lblStsAuthorized:"授权",
  lblStsUnAuthorized:"未经授权",
  lblStsLocked:"已锁定",
  lblStsGuest:"客人",
  lblAuhotrInfo:"授权信息",
  lblOperInfo:"运营信息",
  lblSessId:"会话ID",
  lblReauthPeriod:"重新认证<br>时期",
  lblInactTimeout:"无效<br>超时",
  lblSessTime:"会话<br>时间",
  lblInactedTime:"非活动<br>时间",
  lblQuietTime:"安静<br>时间"
},
<!--#endif-->

/* Common Message */
lang_common: {
ethernet_switch:"以太网交换机",
	error_msg:"错误提示",
	warning_msg:"警告提示",
  txtEnable:"启用",
  txtDisable:"禁用",
  txtEnabled:"已启用",
  txtDisabled:"已禁用",
  txtHexRangeArg:"($1 - $1十六进制字符)",
  txtDefaultArg:"(默认：$1)",
  txtRangeArg:"($1 - $2)",
  txtRangeArgDefault:"($1 - $2，默认 $3)",
  txtRangeArgnot:"($1 - $2, $3 is not set)",
  txtSecRangeArg:"秒($1 - $2)",
  txtMinRangeArg:"最低($1 - $2)",
  txtByteRangeArg:"字节($1 - $2)",
  txtMwRangeArg:"mW ($1 - $2)",
  txtKbpsRangeArg:"Kbps($1 - $2)",
  txtUnitRangeArg:"$1($2 - $3)",
  txtSecRangeArgDefault:"秒($1 - $2，默认$3)",
  txtMinRangeArgDefault:"分钟($1 - $2，default $3)",
  txtMsRangeArgDefault:"毫秒 ($1 - $2, default $3)",
  txtByteRangeArgDefault:"字节($1 -$2，默认$3)",
  txtUnitRangeArgDefault:"$1($2 - $3，默认$4)",
  txtAll:"全部",
  txtAuto:"自动",
  txtArg:"$1",
  btnApply:"应用",
  btnCancel:"取消",
  btnClose:"关闭",
  btnAdd:"添加&nbsp;&nbsp;&nbsp;",
  btnEdit:"编辑&nbsp;&nbsp;&nbsp;",
  btnDelete:"删除",
  tipOnlyOneCanbeEdited:"一次只能处理一个条目.",
  tipNoEntrySelected:"未选择任何条目.",
  btnDetail:"详细信息",
  btnRefresh:"刷新",
  btnPreview:"预览",
  btnClear:"清除",
  btnBack:"返回",
  btnOK:"确定",
  btnDone:"完成",
  btnActive:"活动",
  btnDeactive:"停用",
  btnBind:"绑定",
  btnUnbind:"解除绑定",
  tipProceed:"继续",
  titEditIntfSettings:"编辑界面设置",
  tipButtonTransAdd:"选择要传输的项目",
  tipButtonTransRem:"选择要传输的项目",
  lblEdit:"编辑",
  lblNA:"不适用",
  lblYes:"Yes",
  lblNo:"No",
  lblSave:"保存",
  lblAlert:"警告",
  lblIntfType:"接口类型",
  lblEqualTo:"等于",
  msgNotifySave:"成功",
  msgSuccess:"成功",
  lblOperationalStatus:"运行状态",
  lblMbrPorts:"会员",
  lblPort:"端口",
  lblPortList:"端口列表",
  lblAvailablePort:"可用端口",
  lblSelPort:"选定的端口",
  lblVLAN:"VLAN",
  lblType:"类型",
  lblVlanList:"VLAN列表",
  lblAvailableVlan:"可用VLAN",
  lblSelVlan:"选定的VLAN",
  lblIntfSettingTable:"接口设置表",
  lblNoResultFound:"找到0个结果",
  lblName:"名称",
  lblRange:"范围",
  lblPageLeftCombo:"正在显示",
  lblPageRightCombo:"条目",
  lblIntf:"接口",
  lblLAG:"LAG",
  lblRefreshRate:"刷新率",
  lblRefreshRateSec:"秒",
  lblRefreshRateNone:"无",
  lblRefreshRate5s:"5秒",
  lblRefreshRate10s:"10秒",
  lblRefreshRate30s:"30秒",
  lblUseDefault:"使用默认值",
  lblUserDefined:"用户定义",
  lblSrvAddrType:"地址类型",
  lblByIPAddress:"按IP地址",
  lblByName:"按名称",
  lblHostname:"主机名",
  lblIPv4:"IPv4",
  lblIPv6:"IPv6",
  lblIPVersion:"IP版本",
  lblSrvIPHost:"服务器地址",
  lblSrvPort:"服务器端口",
  lblForward:"转发",
  lblRateLimit:"速率限制",
  lblUnLimited:"无限",
  lblHintUnLimited:"0是无限的",
  lblActionForward:"转发",
  lblActionTrap:"陷阱",
  lblActionLog:"日志",
  lblActionDiscard:"丢弃",
  lblActionShutdown:"关闭",
  lblState:"状态"
},

<!--#ifdef CONFIG_SYS_PROTO_DAI-->
/* DAI*/
lang_dai: {
  lblDAIStatus:"状态",
  titDaiPortSettingTable:"端口设置表",
  titDaiEditPortSetting:"编辑端口设置",
  titTableDaiStatistic:"统计表",
  lblTrusted:"信任",
  lblVerifySrcMac:"源MAC地址",
  lblVerifyDstMac:"目的MAC地址",
  lblVerifyIP:"IP地址",
  lblIPAllowZero:"允许零",
  lblSMacErr:"源MAC <br> 失败",
  lblDMacErr:"目标MAC <br> 失败",
  lblSIPErr:"源IP <br> 验证失败",
  lblDIPErr:"目标IP <br> 验证失败",
  lblIPMACErr:"IP-MAC <br> 不匹配失败"
},
<!--#endif-->

lang_diag: {
  btnCopperTest:"铜缆测试",

  lblPortSelect:"端口",
  lblCopperTestResult:"铜测试结果",
  lblCopperTestStatus:"电缆状态",
  lblCopperResult:"结果",
  lblCopperLength:"长度",
  lblCopperNormal:"确定",
  lblCopperShort:"短电缆",
  lblCopperOpen:"打开电缆",
  lblCopperMisMatch:"阻抗不匹配",
  lblCopperLineDrive:"线路驱动器",
  lblCopperNotTested:"未测试",
  lblMeter:"M",

  btnDetail:"详细信息",
  txtOpticalIntfStatus:"光纤模块状态",
  lblOpticalModuleStatusTable:"光纤模块表",
  lblTransceiverType:"收发器类型",
  lblHotPlug:"热插拔",
  lblConnectorType:"连接器类型",
  lblEthComplianceCode:"以太网合规性代码",
  lblTransmissionMedia:"传输媒体",
  lblWaveLength:"波长",
  lblBitrate:"比特率",
  lblVendorOui:"供应商OUI",
  lblVendorName:"供应商名称",
  lblVendorPN:"供应商PN",
  lblVendorRev:"供应商修订",
  lblVendorSN:"供应商SN",
  lblDateCode:"日期代码",
  lblTemperature:"温度(C)",
  lblVoltage:"电压(V)",
  lblCurrent:"电流(mA)",
  lblOutputPower:"输出功率(mW)",
  lblInputPower:"输入功率(mW)",
  lblLossOfSignal:"信号丢失",
  lblOePresent:"OE 当前",
  lblNA:"N/A",
  lblNS:"N/S",
  lblInsert:"插入",
  lblRemove:"删除",
  lblLoss:"损失",
  lblNormal:"普通",

  btnActivePing:"Ping",
  btnStop:"停止",
  lblPingNum:"计数",
  lblPingResult:"Ping结果",
  lblPingPktStatus:"数据包状态",
  lblPingTx:"传输数据包",
  lblPingRx:"接收数据包",
  lblPingLoss:"丢包",
  lblPingRTT:"往返时间",
  lblPingMinRTT:"最小",
  lblPingMaxRTT:"最大",
  lblPingAvgRTT:"平均",
  lblPingMs:"ms",
  lblPingStatus:"状态",
  lblPingRun:"Ping进行中",
  lblPingTimeout:"Ping失败(超时)",
  lblPingUH:"Ping失败(未知主机)",
  lblPingAbort:"Ping已终止",
  lblTraceTTL:"生存时间(TTL)",
  lblTraceResult:"Traceroute结果",
  txtTraceFailed:"Traceroute失败",
  txtTraceInProgress:"当前正在执行traceroute操作.请稍候,然后重试.",
  txtPingInProgress:"当前正在执行ping操作.请稍候,然后重试.",

  lblTrdpType:"ECNX",
  lblTrdpLocationNumber:"位置"
},

<!--#ifdef CONFIG_SYS_PROTO_DHCPSNOOPING-->
/* DHCP Snooping */
lang_ds: {
  lblDSStatus:"状态",
  lblrelayport:"端口",
  titDsPortSettingTable:"端口设置表",
  titDs82PortSettingTable:"端口设置表",
  titDsEditPortSetting:"编辑端口设置",
  titDs82EditPortSetting:"编辑端口设置",
  titDsStatisticTable:"统计表",
  titDs82CIDTable:"Option82 Circuit ID表",
  titAddOption82CID:"添加Option82 Circuit ID",
  titEditOption82CID:"编辑Option82 Circuit ID",
  lblDsTrusted:"信任",
  lblDsVerifyMac:"验证Chaddr",
  lblChaddrErr:"Chaddr 检查 <br> 丢弃",
  lblUntrustedErr:"不信任端口 <br> 丢弃",
  lblUntrustedOption82Err:"不信任端口 <br> 带Option82 <br> 丢弃",
  lblInvalidErr:"无效的 <br> 丢弃",
  lblRemoteId:"Remote ID",
 lblRemoteIdStrin:"String",
  lblRemoteIdHex:"HEX",

  lblCircuitIdHint:"(保留为空以设置不带VLAN)",
  lblOption82Status:"状态",
  lblOption82Action:"允许不信任",
  lblKeep:"保持",
  lblDrop:"丢弃",
  lblReplace:"替换",
  lblCircuitID:"Circuit ID"
},
<!--#endif-->

/* DoS */
<!--#ifdef CONFIG_SYS_DOS_PROTECTION-->
lang_dos: {
  titDosPortSettingTable:"端口设置表",
  titEditDosPortSetting:"编辑端口设置",
  lblByte:"字节",
  lblNetmaskLen:"网络掩码长度",
  lblDmacEqSmac:"DMAC = SMAC",
  lblLand:"本地",
  lblUdpBlat:"UDP Blat",
  lblTcpBlat:"TCP Blat",
  lblPod:"POD",
  lblIpv6MinFragment:"IPv6最小片段",
  lblIcmpFragment:"ICMP片段",
  lblIpv4PingMaxSize:"IPv4 Ping最大大小",
  lblIpv6PingMaxSize:"IPv6 Ping最大大小",
  lblPingMaxSizeSetting:"Ping最大大小",
  lblipv4PingMaxSizeEnable:"启用IPv4",
  lblipv6PingMaxSizeEnable:"启用IPv6",
  lblSmurfAttack:"Smurf攻击",
  lblTcpMinHdrSize:"TCP最小Hdr大小",
  lblTcpSynSport:"TCP-SYN",
  txtTcpSynSport:"注意：源端口<1024",
  lblNullScanAttack:"Null描攻击",
  lblXMasScanAttack:"X-Mas扫描攻击",
  lblTcpSynFinAttack:"TCP SYN-FIN攻击",
  lblTcpSynRstAttack:"TCP SYN-RST攻击",
  lblTcpFragmentOffset:"TCP片段",
  txtTcpFragmentOffset:"注意：偏移 = 1",
  lblDosPortState:"状态"
},
<!--#endif-->

/* DNS */
<!--#ifdef CONFIG_SYS_ADVANCE_DNS-->
lang_dns: {
  titDnsConf:"DNS Configuration",
  txtDnsStatus:"DNS Status",
  txtDnsDftName:"DNS Default Name",
  txtDnsDftNameLimit:"(<i>1 to 255 alphanumeric characters</i>)",
  titDnsSrvConf:"DNS Server Configuration",
  txtId:"ID",
  txtDnsServer:"DNS Server",
  txtPreference:"Preference",

  titDnsHostConf:"DNS Host Configuration",
  txtHostname:"Host Name (1 to 255 characters)",
  txtIpv4AndIpv6:"IPv4/IPv6 Address",
  txtIpv4:"IPv4 Address",
  titDynamicHostMapping:"Dynamic Host Mapping",
  txtHost:"Host",
  txtTotal:"Total",
  txtElapsed:"Elapsed",
  txtType:"Type"
},

<!--#endif-->

/* Common Error Message */
lang_error: {
  errEmptyValue:"空值无效.",
 	errLengthValue:"字符长度不小于8",
  errNumberChar:"密码需要包含数字，字母或者特殊字符混合组成",
  errOutOfRange:"值超出范围.",
  errOutOfRangeArg:"值超出范围.合法范围为$1-$2.",
  errStrOutOfRange:"输入字符串的大小已达到允许的最大值",
  errInvalidValue:"不是合法的目标值.",
  errInvalidChar:"值包含非法字符.",
  errInvalidMacAddr:"值是非法的MAC地址.",
  errInvalidUnicastMacAddr:"值是一个非法的单播MAC地址.",
  errInvalidIpAddr:"值是一个非法IP地址.",
  errInvalidIpMask:"值是非法的网络掩码.",
  errInvalidUnicastIpAddr:"值是非法的单播IP地址.",
  errInvalidMulticastIpv4Addr:"值是非法的IPv4组播地址",
  errInvalidMulticastIpv4FirstGroup:"第一组的值超出范围.合法范围是224-239",
  errInvalidMulticastIpv6Addr:"值是非法的IPv6组播地址.",
  errInvalidIpv6GroupNum:"IPv6地址的组数无效.",
  errInvalidIpv6Addr:"IPv6地址格式不合法.",
  errInvalidMulticastIpv6FirstGroup:"组1的值应为\"ff00 \"或更高.",
  errInvalidDnsName:"不是有效的DNS名称.正确的语法：Label＃1.Label＃2 ... Label＃n.每个标签的长度介于$1和$2个字符之间.每个标签以字母或数字开头和结尾.",
  errInvalidVlanRangeArg:"目标VLAN不在当前显示的范围内.合法范围：[$1]-[$2]",
  errValMustBePairToPairHexChars:"值必须为$1 .. $2对十六进制字符.",
  errValMustBePairHexChars:"值必须为$1对十六进制字符.",
  errAddEntryFailBecauseTableFull:"由于表已满，因此无法在$ 1表中创建新条目.",
  errEntryAlreadyExists:"条目已存在.",
  errPortBlng2Trunk:"端口$1属于LAG.",
 errDNSLookupFailed:'DNS Lookup failed.',
  errDnsResolveError:"DNS resolution failed. Please check DNS server setting or host name.",
  errDNSDomainErr:"Error! Invalid Domain Name. In Domain Name, each substring must be less than 64 characters in length,separated by a dot and the length of whole string must not exceed 255 characters.",
  errDNSServerMax:"Error! The maximum number of DNS server entries has been already reached.",
  errDNSIPaddr:"Error! Invalid IPv4 or IPv6 Address"
},

/* File Management */
lang_file:{
  lblImage:"Image",
  lblSelImage:"固件",
  lblRunningCfg:"运行配置",
  lblStartupCfg:"启动配置",
  <!--#ifdef CONFIG_SYS_BACKUP_CONFIGURATION-->
  lblBackupCfg:"备份配置",
  <!--#endif-->
  lblFlashLog:"Flash System 日志",
  lblFlashwranLog:"Flash Warning 日志",
	lblRamLog:"RAM System 日志",
  lblRamwranLog:"RAM Warning 日志",

  lblBufferLog:"System 日志",
  lblWarnLog:"Warning 日志",
  lblFileType:"配置",
  lbllogType:"RAM 日志",
  lblflashlogType:"Flash 日志",
  lblAction:"行动",
  lblUpgrade:"升级",
  lblBackup:"备份",
  lblTransferMethod:"方法",
  lblTFTP:"TFTP",
  lblHTTP:"HTTP",
  lblBrowseFile:"文件名",
  lblFileName:"文件名",
  lblSrcFileName:"文件名",
  lblDstFileName:"文件名",
  txtBackupOK:"备份 $1 完成",
  txtBackupFail:"备份 $1 失败",
  txtDownloadInProgress:"正在下载...",
  txtUpgradeOK:"完成升级 $1",
  txtUpgradeFail:"升级$1 失败",
  txtUploadInProgress:"正在上传中...",
  txtUpgradeImgSelActive:"新image在您将其设置为活动image并重新启动系统后使用.",

  lblActImg:"活动Image",
  lblActImgAfterReboot:"注意：该image已选择用于下次启动",
  lblImgActName:"活动Image",
  lblImgBakName:"备份Image",
  lblImgArg:"Image $1",
  lblImgName:"名称",
  lblImgVersion:"版本",
  lblImgSize:"大小",
  lblImgTime:"已创建",
  lblBytesArg:"$1 字节",

  lblSrcFile:"源文件",
  lblDstFile:"目标文件"
},

<!--#ifdef CONFIG_SYS_PROTO_GVRP-->
  /* GVRP */
lang_gvrp:{
  lblGvrpGlobalStatus:"状态",
  lblTableGvrp:"GVRP设置表",
  lblGvrpState:"状态",
  lblGvrDynamicVlan:"VLAN创建",
  lblGvrpRegist:"注册",
  titGVRPPortTbl:"端口设置表",
  lblGvrpState:"状态",
  lblGvrpDynamicVlan:"VLAN创建",
  lblGvrpRegist:"注册",
  lblNormal:"普通",
  lblFixed:"固定",
  lblForbidden:"禁止",
  titEditGVRPPortSetting:"编辑端口设置",
  lblTimeParm:"操作超时",
  lblJoin:"加入",
  lblLeave:"离开",
  lblLeaveAll:"离开所有",

  titGVRPVlanTable:"会员表",
  lblMemberPort:"成员",
  lblDynMemberPort:"动态成员",

  lblcntType:"统计信息",
  lblAll:"全部",
  lblRxCnt:"接收",
  lblTxCnt:"发送",
  lblErrCnt:"错误",

  errGvrpGlobal:"GVRP无法全局启用",
  errGvrpPortmode:"只有VLAN Trunk端口才能启用GVRP",
  errGvrpPortMirror:"无法在镜像目标端口上启用GVRP",
  errGvrpPortType:"启用GVRP的端口必须处于VLAN Trunk模式"
},
<!--#endif-->

/* Link Aggregation */
lang_lag:{
  lblBalance:"负载均衡算法",
  lblBalanceMac:"MAC地址",
  lblBalanceIpMac:"IP-MAC地址",
  titMgmtTbl:"链接汇总表",
  lblType:"类型",
  lblLACP:"LACP",
  lblStatic:"静态",
  lblLinkState:"链接状态",
  lblLagActiveMbrs:"活动成员",
  lblLagInactiveMbrs:"非活动成员",
  titEditLAGGroup:"编辑链接聚合组",
  titLAGPortTbl:"端口设置表",
  titEditLAGPort:"编辑端口设置",
  lblTypeEthArg:"eth$1$2",
  lblLACPSysPriority:"系统优先级",
  titLACPPortTbl:"LACP端口设置表",
  titEditLACPPort:"编辑LACP端口设置",
  lblPortPriority:"端口优先级",
  lblLACPTimeout:"超时",
  lblLong:"长",
  lblShort:"短"
},

/* Line */
lang_line: {
  lblConsole:"Console",
  lblTelnet:"Telnet",
  <!--#ifdef CONFIG_SYS_APP_SSH-->
  lblSsh:"SSH",
  <!--#endif-->
  lblHttp:"HTTP",
  lblHttps:"HTTPS",
  <!--#ifdef CONFIG_SYS_UI_SNMP-->
  lblSnmp:"SNMP",
  <!--#endif-->
  lblMgmtService:"管理服务",
  lblSessTimeout:"会话超时",
  lblPassRetryCnt:"密码重试计数",
  lblSilentTime:"静音时间"
},

<!--#ifdef CONFIG_SYS_PROTO_LLDP-->
/* LLDP */
lang_lldp: {
  lblLLDPProp:"LLDP",
  lblLLDPStatus:"状态",
  lblLLDPFramesHandling:"LLDP处理",
  lblBridging:"桥接",
  lblFiltering:"过滤",
  lblFlooding:"泛洪",
  lblTLVAdvertiseInterval:"TLV通告间隔",
  lblHoldMultiplier:"保持倍增",
  lblReinitialDelay:"重新初始化延迟",
  lblTransmitDelay:"传输延迟",
  <!--#ifdef CONFIG_SYS_PROTO_LLDP_MED--:"Name",>
  lblLLDPMEDProp:"LLDP-MED",
  lblFastStartRepeatCount:"快速启动重复计数",
  <!--#endif-->
  lblAdminStatus:"模式",
  lblSelOptionTLVs:"选定的TLV",
  lblTxOnly:"发送",
  lblRxOnly:"接收",
  lblTxAndRx:"普通",
  titEditLLDPPortSettings:"编辑端口设置",
  lblTLV:"可选TLV",
  lblAvailableOptionTLVs:"可用的TLV",
  lblPortDescription:"端口描述",
  lblSysName:"系统名称",
  lblSysDescription:"系统描述",
  lblSysCapabilities:"系统能力",
  lblMACPHY:"802.3 MAC-PHY",
  lblLinkAggregation:"802.3链路聚合",
  lblMaxFrameSize:"802.3最大帧大小",
  lblMgmtIpAddr:"管理IP地址",
  lblPVIDTLV:"802.1 PVID",
  lblVLANTLV:"802.1 VLAN 名称",

  <!--#ifdef CONFIG_SYS_PROTO_LLDP_MED-->
  lblLLDPMEDNetworkPolicyTable:"MED网络策略表",
  lblNetworkPolicyNum:"策略ID",
  lblApp:"应用",
  lblVlanID:"VLAN",
  lblVlanTag:"VLAN Tag",
  lblUserPriority:"优先级",
  lblDSCPValue:"DSCP",
  lblTagged:"Tagged",
  lblUntagged:"Untaged",
  lblVoice:"语音",
  lblVoiceSignaling:"语音信号",
  lblGuestVoice:"访客语音",
  lblGuestVoiceSignaling:"访客语音信号",
  lblSoftphoneVoice:"软件电话语音",
  lblVideoConferencing:"视频会议",
  lblStreamingVideo:"流媒体视频",
  lblVideoSignaling:"视频信令",
  titAddLLDPMEDNetworkPolicy:"添加MED网络策略",
  titEditLLDPMEDNetworkPolicy:"编辑MED网络策略",

  lblLLDPMEDPortSettingTable:"MED端口设置表",
  lblLLDPMEDStatus:"状态",
  lblUserDefinedNetworkPolicy:"网络策略",
  lblLocation:"位置",
  lblInventory:"库存",
  lblActive:"活动",
  lblYes:"是",
  lblNo:"否",
  titEditLLDPMEDPortSettings:"编辑MED端口设置",
  lblNetworkPolicy:"网络策略",
  lblAvailableNetworkPolicies:"可用策略",
  lblSelNetworkPolicies:"选定的策略",
  lblCivic:"Civic",
  lblCoordinates:"坐标",
  lblECSELIN:"ECS ELIN",
  lbl16PairsHexChars:"(16对十六进制字符)",
  lbl6to160PairsHexChars:"(6-160对十六进制字符)",
  lbl10to25PairsHexChars:"(10-25对十六进制字符)",
  <!--#endif-->

  titLldpPacketView:"数据包视图表",
  lblTotalBytesInUse:"使用中(字节)",
  lblAvailableBytesLeft:"可用(字节)",
  lblStatus:"运行状态",
  lblOverloading:"过载",
  lblNotOverloading:"未超载",
  titLLDPOverloadingDetails:"数据包视图详细信息",
  lblLLDPMandatoryTLV:"强制性TLV",
  lblLLDPMEDCapabilities:"MED功能",
  lblLLDPMEDLocation:"MED位置",
  lblLLDPMEDNetworkPolicy:"MED网络策略",
  lblLLDPMEDExtendedPowerViaMDI:"通过MDI的MED扩展电源",
  lblDot3Tlvs:"802.3 TLV",
  lblLLDPOptionalTLV:"可选TLV",
  lblLLDPMEDInventory:"MED库存",
  lblDot1Tlvs:"802.1 TLV",
  lblTransmitted:"已发送",
  lblSizeBytes:"大小(字节)",
  lblTotalBytes:"总计(字节)",

  titLocalSummary:"设备摘要",
  btnLLDPPortStatusTable:"端口状态表",
  lblLLDPState:"LLDP状态",
  lblLLDPMEDState:"LLDP-MED状态",
  btnLLDPLocalInfoDetail:"本地信息详细信息",
  lblChassisIDSubtype:"Chassis ID子类型",
  lblChassisID:"Chassis ID",
  lblSupportedSysCapabilities:"支持的功能",
  lblEnabledSysCapabilities:"已启用功能",
  lblPortIDSubtype:"端口ID子类型",
  lblChassisComponent:"机箱组件",
  lblIntfAlias:"接口别名",
  lblPortComponent:"端口组件",
  lblMacAddr:"MAC地址",
  lblNetworkAddr:"网络地址",
  lblIntfName:"接口名称",
  lblAgentCircuitID:"代理circuit ID",
  lblLocal:"本地",
  lblOther:"其他",
  lblRepeater:"中继器",
  lblBridge:"桥梁",
  lblL3:"Bridge, Router",
  lblWLANAccessPoint:"WLAN接入点",
  lblRouter:"路由器",
  lblTelephone:"电话",
  lblDOCSISCableDevice:"DOCSIS电缆设备",
  lblStationOnly:"仅工作站",
  lblPowerSourcingEntity:"电源实体",
  lblPoweredDevice:"受电设备",
  lblUnknown:"未知",
  lblPrimaryPowerSource:"主电源",
  lblBackupPowerSource:"备份电源",
  lblFromPSE:"来自PSE",
  lblLocalAndPSE:"本地和PSE",
  lblCritical:"关键",
  lblHigh:"高",
  lblLow:"低",
  lblWatts:"$1.$2 Watts",
  lblFromPowerSourcingEntity:"来自电源实体",
  lblLocalAndFromPowerSourcingEntity:"本地和源电源实体",
  tipNoNeighbors:"无邻居",

  lblPortID:"端口ID",
  lblPortDescription:"端口描述",
  lblMgmtAddrTable:"管理地址表",
  lblAddrSubtype:"地址子类型",
  lblAddr:"地址",
  lblIntfSubtype:"接口子类型",
  lblIntfNum:"接口号",
  lblIPv4:"IPv4",
  lblIPv6:"IPv6",
  lblNsap:"nsap",
  lblHdlc:"hdlc",
  lblBbn1822:"bbn1822",
  lblAll802:"all802",
  lblE163:"e163",
  lblE164:"e164",
  lblF69:"f69",
  lblX121:"x121",
  lblIpx:"ipx",
  lblAppleTalk:"Apple Talk",
  lblDecentIV:"DecentIV",
  lblBanyanVines:"Banyan Vines",
  lblE164WithNsap:"e164带Nsap",
  lblDNS:"DNS",
  lblDistinguishedName:"专有名称",
  lblAsNum:"如数字",
  lblXtpOverIpv4:"xtp 超过 Ipv4",
  lblXtpOverIpv6:"xtp 超过 Ipv6",
  lblXtpNativeModeXtp:"xtp本地模式XTP",
  lblIfIndex:"接口索引",
  lblSysPortNum:"系统端口号",
  lblMACPHYDetail:"MAC/PHY详细信息",
  lblAutoNegoSupported:"支持自动协商",
  lblAutoNegoEnabled:"已启用自动协商",
  lblTrue:"真",
  lblFalse:"假",
  lblAutoNegoAdvertised:"自动协商广告功能",
  lblOperMAUType:"操作性MAU类型",

  lbl10BaseT:"10baseT",          
  lbl10BaseTFD:"10baseTFD",      
  lbl100BaseT4:"100baseT4",      
  lbl100BaseTX:"100baseTX",      
  lbl100BaseTXFD:"100baseTXFD",  
  lbl100BaseT2:"100baseT2",
  lbl100BaseT2FD:"100baseT2FD",
  lblFdxPause:"FdxPause",
  lblFdxAPause:"FdxAPause",
  lblFdxSPause:"FdxSPause",
  lblFdxBPause:"FdxBPause",
  lbl1000BaseX:"1000baseX",
  lbl1000BaseXFD:"1000baseXFD",
  lbl1000BaseT:"1000baseT",
  lbl1000BaseTFD:"1000baseTFD",

  lblMauAui:"dot3MauTypeAUI",
  lblMau10Base5:"dot3MauType10Base5",
  lblMau10Foirl:"dot3MauTypeFoirl",
  lblMau10Base2:"dot3MauType10Base2",
  lblMau10BaseT:"dot3MauType10BaseT",
  lblMau10BaseFP:"dot3MauType10BaseFP",
  lblMau10BaseFB:"dot3MauType10BaseFB",
  lblMau10BaseFL:"dot3MauType10BaseFL",
  lblMau10Broad36:"dot3MauType10Broad36",
  lblMau10BaseTHD:"dot3MauType10BaseTHD",
  lblMau10BaseTFD:"dot3MauType10BaseTFD",
  lblMau10BaseFLHD:"dot3MauType10BaseFLHD",
  lblMau10BaseFLFD:"dot3MauType10BaseFLFD",
  lblMau100BaseT4:"dot3MauType100BaseT4",
  lblMau100BaseTXHD:"dot3MauType100BaseTXHD",
  lblMau100BaseTXFD:"dot3MauType100BaseTXFD",
  lblMau100BaseFXHD:"dot3MauType100BaseFXHD",
  lblMau100BaseFXFD:"dot3MauType100BaseFXFD",
  lblMau100BaseT2HD:"dot3MauType100BaseT2HD",
  lblMau100BaseT2FD:"dot3MauType100BaseT2FD",
  lblMau1000BaseXHD:"dot3MauType1000BaseXHD",
  lblMau1000BaseXFD:"dot3MauType1000BaseXFD",
  lblMau1000BaseLXHD:"dot3MauType1000BaseLXHD",
  lblMau1000BaseLXFD:"dot3MauType1000BaseLXFD",
  lblMau1000BaseSXHD:"dot3MauType1000BaseSXHD",
  lblMau1000BaseSXFD:"dot3MauType1000BaseSXFD",
  lblMau1000BaseCXHD:"dot3MauType1000BaseCXHD",
  lblMau1000BaseCXFD:"dot3MauType1000BaseCXFD",
  lblMau1000BaseTHD:"dot3MauType1000BaseTHD",
  lblMau1000BaseTFD:"dot3MauType1000BaseTFD",
  lblMau10GigBaseX:"dot3MauType10GigBaseX",
  lblMau10GigBaseLX4:"dot3MauType10GigBaseLX4",
  lblMau10GigBaseR:"dot3MauType10GigBaseR",
  lblMau10GigBaseER:"dot3MauType10GigBaseER",
  lblMau10GigBaseLR:"dot3MauType10GigBaseLR",
  lblMau10GigBaseSR:"dot3MauType10GigBaseSR",
  lblMau10GigBaseW:"dot3MauType10GigBaseW",
  lblMau10GigBaseEW:"dot3MauType10GigBaseEW",
  lblMau10GigBaseLW:"dot3MauType10GigBaseLW",
  lblMau10GigBaseSW:"dot3MauType10GigBaseSW",

  lblDot3Details:"802.3详细信息",
  lblDot3MaxFrameSize:"802.3最大帧大小",
  lblDot3LinkAggregation:"802.3链路聚合",
  lblAggregationCapability:"聚合能力",
  lblAggregationStatus:"聚合状态",
  lblAggregationPortID:"聚合端口ID",
  lblCapable:"有能力",
  lblNotCapable:"不具备",
  lblAggr:"聚合",
  lblNotAggr:"非聚合",

  <!--#ifdef CONFIG_SYS_PROTO_LLDP_MED-->
  lblMEDDetails:"MED详细信息",
  lblCapabilitiesSupported:"支持的功能",
  lblCurrentCapabilities:"当前功能",
  lblDeviceClass:"设备类别",
  lblDot3PowerType:"电源类型",
  lblDot3PowerSource:"电源",
  lblDot3PowerPriority:"电源优先级",
  lblRequestPowerValue:"PD请求功率值",
  lblAllocatedPowerValue:"PSE分配的功率值",
  lblPoEDeviceType:"PoE设备类型",
  lblPoEPowerSource:"PoE电源",
  lblPoEPowerPriority:"PoE电源优先级",
  lblPoEPowerValue:"PoE功率值",
  lblHardwareRevision:"硬件修订",
  lblFirmwareRevision:"固件版本",
  lblSoftwareRevision:"软件版本",
  lblSerialNumber:"序列号",
  lblManufacturerName:"制造商名称",
  lblModelName:"型号名称",
  lblAssetID:"资产ID",
  lblCapabilities:"功能",
  lblNetworkPolicy:"网络策略",
  lblExtPSE:"扩展的PSE",
  lblExtPD:"扩展PD",
  lblNotDef:"未定义",
  lblEndClass1:"端点Class 1",
  lblEndClass2:"端点Class 2",
  lblEndClass3:"端点Class 3",
  lblNetCon:"网络连接",
  lblLocationInfo:"位置信息",
  lblNetworkPolicyTable:"网络策略表",
  lblAppType:"应用程序类型",
  lblVlanType:"VLAN类型",
  lblDSCP:"DSCP",
  <!--#endif-->

  btnNeighborTable:"邻居表",
  btnLLDPNeighborDetail:"邻居信息详细信息",
  lblLocalPort:"本地端口",
  lblTTL:"生存时间TTL",
  lblLLDPNeighborInfo:"LLDP邻居信息",
  lblPortDetails:"端口详细信息",
  lblMSAPEntry:"MSAP条目",
  lblBasicDetails:"基本细节",
  lblDot3PowerViaMDI:"802.3通过MDI供电",
  lblMDIPowerSupportPortClass:"MDI电源支持端口类",
  lblPSEMDIPowerSupport:"PSE MDI电源支持",
  lblPSEMDIPowerState:"PSE MDI电源状态",
  lblPSEPowerPairControlAbility:"PSE电源对控制功能",
  lblPSEPowerPair:"PSE电源对",
  lblPSEPowerClass:"PSE功率等级",
  lblSignal:"信号",
  lblSpare:"备用",
  lblClassPSE:"pClassPSE",
  lblClassPD:"pClassPD",
  lblSupported:"支持",
  lblNotSupported:"不支持",
  lblEnabled:"已启用",
  lblDisabled:"已禁用",
  lblClass:"Class $1",
  lblDot1VlanAndProtocol:"802.1 VLAN协议",
  lblPVID:"PVID",
  lblPPVID:"PPVIDs",
  lblPPVIDTable:"PPVID表",
  lblVID:"VID",
  lblSupported:"支持",
  lblVlanIDs:"VLAN ID",
  lblVlanIDTable:"VLAN ID表",
  lblVlanName:"VLAN名称",
  lblProtocolIDs:"协议ID",
  lblProtocolIDTable:"协议ID表",
  lblProtocolID:"协议ID",

  titLLDPGlobalStatististics:"全部统计",
  lblInsertions:"插入",
  lblDeletions:"删除",
  lblDrops:"Drops",
  lblAgeOuts:"AgeOuts",
  lblLLDPStatisticsTable:"统计表",
  lblTxFrames:"传输帧",
  lblRxFrames:"接收帧",
  lblRxTLVs:"接收TLV",
  lblNeighborInfoDeleteCnt:"邻居<br>超时",
  lblTotal:"总计",
  lblDiscarded:"丢弃",
  lblErrors:"错误",
  lblUnrecognized:"无法识别"
},
<!--#endif-->

<!--#ifdef CONFIG_SYS_SYSLOG-->
lang_log:{
  lblLoggingTable:"记录消息表",
  lblLoggingType:"查看",
  txtRam:"RAM",
  txtFile:"Flash",
  lblLogIdx:"日志ID",
  lblLogTime:"时间",
  lblLogSev:"严重性",
  lblLogDesc:"说明",
  lblState:"状态",
  lblAggregation:"聚合",
  lblAggAgingTime:"老化时间",
  lblConsoleLogging:"Console日志",
  lblRamLogging:"RAM日志",
  lblFileLogging:"Flash日志",
  lblMinSev:"最低&nbsp<br>严重程度",
  lblRemoteLogServerTable:"远程服务器表",
  lblLogServer:"日志服务器",
  lblFacility:"设备",
  lblLocalArg:"本地$1",
  titAddRemoteLogServer:"添加远程服务器",
  titEditRemoteLogServer:"编辑远程服务器",
  txtEmergency:"紧急",
  txtAlert:"警惕",
  txtCritical:"关键",
  txtError:"错误",
  txtWarning:"警告",
  txtNotice:"通知",
  txtInformational:"信息",
  txtDebug:"Debug"
},
<!--#endif-->

<!--#ifdef CONFIG_SYS_PROTO_ISG-->
/* IP Source Guard */
lang_ipsg: {
  titIPSGSetting:"端口设置表",
  titIPSGEditPortSetting:"编辑端口设置",
  titIPSGBinding:"IP-MAC-端口-VLAN绑定表",
  titBindingEntryAdd:"添加IP-MAC-端口-VLAN绑定",
  titBindingEntryEdit:"编辑IP-MAC-端口-VLAN绑定",
  lblStatus:"状态",
  lblVerifySrc:"验证源",
  lblCurEntryNo:"当前条目",
  lblMaxEntryNo:"最大入口",
  lblVerifySrcIP:"IP",
  lblVerifySrcMACIP:"IP-MAC",
  lblIPSGBinding:"绑定",
  lblIPPort:"IP端口VLAN",
  lblIPMacPort:"IP-MAC-Port-VLAN",
  lblMACAddr:"MAC地址",
  lblIPAddr:"IP地址",
  lblType:"类型",
  lblLeaseTime:"租赁时间",
  lblTypeStatic:"静态",
  lblTypeDynamic:"动态",
  lblBKDBType:"类型",
  lblBKDBTypeNone:"无",
  lblBKDBTypeFlash:"Flash",
  lblBKDBTypeTFTP:"TFTP",
  lblBKDBFileName:"文件名",
  lblBKDBWriteDelay:"写入延迟",
  lblBKDBTimeout:"超时"
},
<!--#endif-->

lang_mac:{
  titMacAddressTable:"MAC地址表",
  titDynamicAddressTable:"动态地址表",
  titStaticMacTable:"静态地址表",
  titStaticMacAdd:"添加静态地址",
  titStaticMacEdit:"编辑静态地址",
  titAddressFilterTable:"过滤地址表",
  titAddressFilterAdd:"添加过滤地址",
  titAddressFilterEdit:"编辑过滤地址",
  lblAgingTime:"老化时间",
  lblAddToStatic:"添加静态地址",
  lblMac:"MAC地址",
  lblType:"类型",
  lblCpuPort:"CPU",
  lblMacTypeManage:"管理",
<!--#ifdef CONFIG_SYS_BLACK_HOLE_MAC-->
  lblMacTypeBlacklist:"Drop",
<!--#endif-->
<!--#ifdef CONFIG_SYS_PROTO_AUTHMGR-->
  lblMacTypeAuth:"Auth",
<!--#endif-->
<!--#ifdef CONFIG_SYS_PORT_SECURITY-->
  lblMacTypeSecureDynamic:"SecureDynamic",
  lblMacTypeSecureSticky:"SecureSticky",
  lblMacTypeSecureConfigured:"SecureConfigured",
<!--#endif-->
  lblMacTypeStatic:"静态",
  lblMacTypeDynamic:"动态"
  },

/* Menu tree */
lang_menu: {
  fld1Status:"状态",
  doc1StatusInfo:"系统信息",
  doc1StatusSyslog:"记录消息",
  fld2StatusPort:"端口",
  doc2StatusPortCnt:"统计信息",
  <!--#ifdef CONFIG_SYS_PORT_ERR_DISABLED-->
  doc2StatusPortErrDisable:"错误已禁用",
  <!--#endif-->
  doc2StatusPortBwUtiliz:"带宽利用率",
  doc1StatusLAG:"链接聚合",
  doc1StatusMac:"MAC地址表",
  doc1BindUsername:"云端绑定状态",

  fld1Network:"网络",
  doc1NetworkIPAddr:"IP地址",
  <!--#ifdef CONFIG_SYS_ADVANCE_DNS-->
  doc1NetworkDNS:"DNS",
  doc1NetworkDNSHosts:"Hosts",
  <!--#endif-->
  doc1NetworkTimeSys:"系统时间",

  fld1Port:"端口",
  doc1PortSetting:"端口设置",
  <!--#ifdef CONFIG_SYS_PORT_ERR_DISABLED-->
  doc1PortErrDisable:"错误已禁用",
  <!--#endif-->
  fld2PortLAG:"链接聚合",
  doc2PortLAGMgmt:"组",
  doc2PortLAGPort:"端口设置",
  doc2PortLACP:"LACP",
  <!--#ifdef CONFIG_SYS_EEE-->
  doc1PortEEE:"EEE",
  <!--#endif-->
  doc1PortJumbo:"巨型帧",

  fld1PoE:"PoE",
  doc1PoESetting:"PoE 设置",
	fld1ERPS:"ERPS",
  doc1ErpsSetting:"ERPS 设置",

  fld1ERPS:"ERPS",
  doc1ErpsSetting:"ERPS Setting",
  fld1Vlan:"VLAN",
  fld2Vlan:"VLAN",
  doc1VlanCreate:"创建VLAN",
  doc1VlanVLANConf:"VLAN配置",
  doc1VlanMembership:"成员资格",
  doc1VlanPort:"端口设置",

  <!--#ifdef CONFIG_SYS_VOICEVLAN-->
  fld2VlanVoice:"语音VLAN",
  doc2VlanVoiceProp:"属性",
  doc2VlanVoiceOUI:"语音OUI",
  <!--#endif-->
  <!--#ifdef CONFIG_SYS_PROTOCOL_VLAN-->
  fld2VlanProtocol:"协议VLAN",
  doc1VlanProtoGroup:"协议组",
  doc1VlanProtoPort:"组绑定",
  <!--#endif-->
  <!--#ifdef CONFIG_SYS_MACVLAN-->
  fld2VlanMac:"MAC VLAN",
  doc1VlanMacGroup:"MAC组",
  doc1VlanMacGroupMapping:"组绑定",
  <!--#endif-->
  <!--#ifdef CONFIG_SYS_SURVEILLANCEVLAN-->
  fld2VlanSurveillance:"Surveillance VLAN",
  doc2VlanSurveillanceProp:"属性",
  doc2VlanSurveillanceOUI:"Surveillance OUI",
  <!--#endif-->
  <!--#ifdef CONFIG_SYS_PROTO_GVRP-->
  fld2VlanGVRP:"GVRP",
  doc2VlanGVRPProperty:"属性",
  doc2VlanGVRPMembership:"成员",
  doc2VlanGVRPStatistics:"统计信息",
  doc2VlanGVRPErrorStatistics:"错误统计信息",
  <!--#endif-->

  fld1Mac:"MAC地址表",
  doc1MacDynamic:"动态地址",
  doc1MacStatic:"静态地址",
  doc1MacFilter:"过滤地址",
  <!--#ifdef CONFIG_SYS_PORT_SECURITY-->
  doc1MacPsecure:"Port Security Address",
  <!--#endif-->

  fld1STP:"生成树",
  doc1StpGlobal:"属性",
  doc1StpIntf:"端口设置",
  <!--#ifdef CONFIG_SYS_PROTO_STP_MSTP-->
  doc1StpMstInstance:"MST实例",
  doc1StpMstIntf:"MST端口设置",
  <!--#endif-->
  doc1StpStatistics:"统计信息",

  <!--#ifdef CONFIG_SYS_PROTO_LLDP-->
  fld1Discov:"发现",
  fld2DiscovLLDP:"LLDP",
  doc2DiscovLLDPProp:"属性",
  doc2DiscovLLDPPort:"端口设置",
  <!--#ifdef CONFIG_SYS_PROTO_LLDP_MED-->
  doc2DiscovLLDPMedPolicy:"MED网络策略",
  doc2DiscovLLDPMedPort:"MED端口设置",
  <!--#endif-->
  doc2DiscovLLDPOverloading:"数据包视图",
  doc2DiscovLLDPLocalInfo:"本地信息",
  doc2DiscovLLDPNeighbor:"邻居",
  doc2DiscovLLDPStatistics:"统计信息",
  <!--#endif-->

  fld1Mcast:"组播",
  fld2McastGeneral:"常规",
  doc2McastGeneralProperty:"属性",
  doc2McastGeneralGroupAddr:"组地址",
  doc2McastGeneralRate:"限速",
  doc2McastGeneralRouterPort:"路由端口",
  <!--#ifdef CONFIG_SYS_PROTO_IGMP_STATIC_FORWARD-->
  doc2McastGeneralForwardAll:"全部转发",
  <!--#endif-->
  <!--#ifdef CONFIG_SYS_PROTO_IGMP_THROTTLING-->
  doc2McastGeneralThrottling:"限制",
  <!--#endif-->
  <!--#ifdef CONFIG_SYS_PROTO_IGMP_FILTERING-->
  doc2McastIGMPGeneralFilterProfile:"过滤信息",
  doc2McastIGMPGeneralFilterBinding:"过滤绑定",
  <!--#endif-->
  fld2McastIGMP:"IGMP Snooping",
  doc2McastIGMPProperty:"属性",
  doc2McastIGMPQuerier:"查询器",
  doc2McastIGMPStatistics:"统计信息",
  <!--#ifdef CONFIG_SYS_PROTO_MLD_SNOOPING-->
  fld2McastMLD:"MLD Snooping",
  doc2McastMLDProperty:"属性",
  doc2McastMLDStatistics:"统计信息",
  <!--#endif-->
  <!--#ifdef CONFIG_SYS_PROTO_MVR-->
  fld2McastMVR:"MVR",
  doc2McastMVRProperty:"属性",
  doc2McastMVRPortSetting:"端口设置",
  doc2McastMVRGroupAddress:"组地址",
  <!--#endif-->

  <!--#ifdef CONFIG_SYS_L3_ROUTE-->
  fld1IPConfig:"路由",
  fld2IPv4:"IPv4 接口和管理",
  doc2IPv4Intf:"IPv4 接口",
  doc2IPv4Route:"IPv4 路由",
  doc2IPv4Arp:"ARP",
  doc2IPv4ArpProxy:"ARP 代理",
  fld2IPv6:"IPv6 接口和管理",
  doc2IPv6Intf:"IPv6 接口",
  doc2IPv6Addr:"IPv6 地址",
  doc2IPv6Route:"IPv6 路由",
  doc2IPv6Neigh:"IPv6 邻居",
  <!--#endif-->
  fld1Sec:"安全",
  <!--#ifdef CONFIG_SYS_LIB_RADIUS-->
  doc1SecRadius:"RADIUS",
  <!--#endif-->
  <!--#ifdef CONFIG_SYS_LIB_TACPLUS-->
  doc1SecTacplus:"TACACS+",
  <!--#endif-->
  <!--#ifdef CONFIG_SYS_AAA-->
  fld2SecAAA:"AAA",
  doc2SecAAALoginList:"方法列表",
  doc2SecAAALoginAuthen:"登录身份验证",
  <!--#endif-->
  fld2SecMgmtAccess:"管理访问权限",
  doc2SecMgmtVLAN:"管理VLAN",
  doc2SecMgmtService:"管理服务",
  <!--#ifdef CONFIG_SYS_MGMT_ACL-->
  doc2SecMgmtACL:"管理ACL",
  doc2SecMgmtACE:"管理ACE",
  <!--#endif-->
  <!--#ifdef CONFIG_SYS_PROTO_AUTHMGR-->
  fld2SecAuthmgr:"身份验证管理器",
  doc2SecAuthmgrProp:"属性",
  doc2SecAuthmgrPort:"端口设置",
  doc2SecAuthmgrMacLocal:"基于MAC的本地帐户",
  doc2SecAuthmgrWebLocal:"基于WEB的本地帐户",
  doc2SecAuthmgrSess:"会话",
  <!--#endif-->
  <!--#ifdef CONFIG_SYS_PORT_SECURITY-->
  doc1SecPort:"端口安全",
  <!--#endif-->
  <!--#ifdef CONFIG_SYS_PORT_ISOLATION-->
  doc1SecProtected:"受保护的端口",
  <!--#endif-->
  doc1SecStorm:"风暴控制",
  <!--#ifdef CONFIG_SYS_DOS_PROTECTION-->
  fld2SecDos:"DoS",
  doc2SecDosProp:"属性",
  doc2SecDosPort:"端口设置",
  <!--#endif-->
  <!--#ifdef CONFIG_SYS_PROTO_ISG-->
  fld2SecISG:"IP源防护",
  doc2SecISGPort:"端口设置",
  doc2SecISGBind:"IMPV绑定",
  doc2SecISGDatabase:"保存数据",
  <!--#endif-->
  <!--#ifdef CONFIG_SYS_PROTO_DAI-->
  fld2SecDAI:"动态ARP检查",
  doc2SecDAI:"属性",
  doc2SecDAIStatistic:"统计信息",
  <!--#endif-->
  <!--#ifdef CONFIG_SYS_PROTO_DHCPSNOOPING-->
  fld2SecDS:"DHCP Snooping",
  doc2SecDS:"属性",
  doc2SecDSRelay:"DHCP Relay",
  doc2SecDSStatistic:"统计信息",
  doc2SecDSOpt82Global:"Option82属性",
  doc2SecDSOpt82Circuit:"Option82 Circuit ID",
  <!--#endif-->

 <!--#ifdef CONFIG_SYS_USER_DEFINED_ACL-->
  fld1Acl:"ACL",
  doc1AclMAC:"MAC ACL",
  doc1AclMACAce:"MAC ACE",
  doc1AclIPv4:"IPv4 ACL",
  doc1AclIPv4Ace:"IPv4 ACE",
  doc1AclIPv6:"IPv6 ACL",
  doc1AclIPv6Ace:"IPv6 ACE",
  doc1AclBind:"ACL绑定",
  <!--#endif-->

  fld1Qos:"QoS",
  fld2QosGeneral:"常规",
  doc2QosGeneralProp:"属性",
  doc2QosGeneralQueue:"队列调度",
  doc2QosGeneralCoS:"CoS映射",
  doc2QosGeneralDSCP:"DSCP映射",
  doc2QosGeneralIPP:"IP优先级映射",
  fld2QosRate:"速率限制",
  doc2QosRateBwctl:"入口/出口",
  doc2QosRateEgressQueue:"出口队列",

  fld1Diag:"诊断",
  fld2DiagLog:"日志记录",
  doc2DiagLogProp:"属性",
  doc2DiagLogRemote:"远程服务器",
  doc1DiagMirror:"镜像",
  doc1DiagPing:"Ping",
  doc1DiagTrdp:"Trdp",
  doc1DiagTraceRoute:"Traceroute",
  doc1DiagCopper:"铜缆测试",
  <!--#ifdef CONFIG_SYS_OPTICALMOD_STATUS-->
  doc1DiagFiber:"光纤模块",
  doc1Alarm:"告警设置",
  <!--#endif-->
  <!--#ifdef CONFIG_SYS_PROTO_UDLD-->
  fld2SecUDLD:"UDLD",
  doc2SecUDLDProp:"属性",
  doc2SecUDLDNeighbors:"邻居",
  <!--#endif-->
  doc1DiagReboot:"重新启动",

  fld1Mgmt:"管理",
  doc1MgmtAccount:"用户帐户",
  fld2MgmtFirmware:"固件",
  doc2MgmtUpgradeBackup:"升级/备份",
  doc2MgmtActiveImg:"活动Image",
  fld2MgmtConfig:"配置",
  doc2MgmtConfigSave:"保存配置",
  <!--#ifdef CONFIG_SYS_UI_SNMP-->
  fld2MgmtSNMP:"SNMP",
  <!--#ifdef CONFIG_SYS_SNMPV3-->
  doc2MgmtSNMPView:"查看",
  doc2MgmtSNMPGroup:"组",
  doc2MgmtSNMPCommunity:"Community",
  doc2MgmtSNMPUser:"用户",
  doc2MgmtSNMPEngine:"Engine ID",
  doc2MgmtSNMPTrapEvent:"Trap 事件",
  doc2MgmtSNMPNotify:"通知",
  <!--#else-->
  doc2MgmtSNMPCommunity:"Community",
  doc2MgmtSNMPTrapEvent:"Trap事件",
  doc2MgmtSNMPNotify:"通知",
  <!--#endif-->
  <!--#endif-->
  <!--#ifdef CONFIG_SYS_MIB_RMON_MGMT_UI-->
  fld2MgmtRMON:"RMON",
  doc2MgmtRMONStatistic:"统计信息",
  doc2MgmtRMONEvent:"事件",
  doc2MgmtRMONAlarm:"警报",
  doc2MgmtRMONHistory:"历史记录",
  <!--#endif-->
  dummy:""
},

lang_mcast:{
  lblUnknownMcastAct:"未知组播&nbsp<br>操作",
  lblDrop:"丢弃",
  lblFlood:"泛洪",
  lblForwardToRouterPort:"转发到路由端口",
  lblFwdMethod:"组播转发方式",
  lblDmac:"DMAC-VID",
  lblDip:"DIP-VID",

  <!--#ifdef CONFIG_SYS_PROTO_MLD_SNOOPING-->
  txtIPv4:"IPv4",
  txtIPv6:"IPv6",
  lblMLDv1:"MLDv1",
  lblMLDv2:"MLDv2",
  <!--#endif-->

  lblMcastGrpTable:"组地址表",
  lblMcastGroupAddr:"组地址",
  lblMcastGroupmac:"组MAC地址",
  lblMemberPort:"成员",
  lblStatic:"静态",
  lblForbid:"禁止",
  lblNone:"无",
  lblDynamic:"动态",
  lblForbidden:"禁止",
  lblType:"类型",
  lblLifeSec:"生命(秒)",
  lblRate:"限速(Kps)",
  lblRates:"限速",
  titEditGroup:"Edit Group Address",
  titAddGroup:"Add Group Address",

  titEditGroup:"编辑组地址",
  titAddGroup:"添加组地址",

  lblMcastRouterTable:"路由端口表",
  lblRtMbrPort:"端口",
  <!--#ifdef CONFIG_SYS_PROTO_IGMP_STATIC_ROUTER-->
  titAddRouter:"添加路由端口",
  titEditRouter:"编辑路由端口",
  lblStRtMbrPort:"静态端口",
  lblForbidRtMbrPort:"禁止的端口",
  lblRtMbrPortType:"类型",
  <!--#endif-->

  <!--#ifdef CONFIG_SYS_PROTO_IGMP_STATIC_FORWARD-->
  lblMcastFwdAllTable:"转发所有的表",
  titAddFwdAll:"添加全部转发",
  titEditFwdAll:"编辑全部转发",
  lblStFwdMbrPort:"静态端口",
  lblForbidFwdMbrPort:"禁止的端口",
  <!--#endif-->

  <!--#ifdef CONFIG_SYS_PROTO_IGMP_THROTTLING-->
  lblDeny:"拒绝",
  lblReplace:"替换",
  txtMcastThrotTable:"限制表",
  txtEditMcastThrotTable:"编辑节流",
  lblMaxGroup:"最大组",
  lblMaxAct:"超出动作",
  <!--#endif-->

  <!--#ifdef CONFIG_SYS_PROTO_IGMP_FILTERING-->
  titProfilesTable:"过滤配置文件表",
  lblProfileIndex:"个人资料ID",
  lblStartMulticastAddr:"起始地址",
  lblEndMulticastAddr:"结束地址",
  lblAction:"动作",
  lblAllow:"允许",
  lblProfDeny:"拒绝",
  titAddProfiles:"添加个人资料",
  titEditProfile:"编辑配置文件",

  titMulticastFilterTable:"过滤绑定表",
  titEditFilterSettings:"编辑过滤绑定",
  lblFilterProfileIndex:"个人资料ID",
 <!--#endif-->

  lblMcastState:"状态",
  lblMcastVersion:"版本",
  lblIGMPv1:"IGMPv1",
  lblIGMPv2:"IGMPv2",
  lblIGMPv3:"IGMPv3",

  lblReportSuppression:"报告抑制",
  titMcastVlan:"VLAN设置表",
  tblMRouterPortsAutoLearn:"路由端口<br>自动学习",
  tblForbiddenPorts:"禁止<br>端口",
  tblForbiddenMRouterPorts:"禁止<br>路由端口",
  tblQueryRobustness:"查询<br>稳健性",
  tblQueryInterval:"查询<br>间隔",
  tblQueryMaxResponseInterval:"查询最大<br>响应间隔",
  tblLastMemberQueryCounter:"最后一个成员<br>查询计数器",
  tblLastMemberQueryInterval:"最后一个成员<br>查询间隔",
  tblImmediateLeave:"立即离开",
  titQuerierTable:"查询表",
  titQuerierTableEdit:"编辑查询器",
  tblIGMPQuerierState:"状态",
  tblIGMPQuerierStatus:"操作状态",
  tblIGMPQuerierVersion:"版本",
  tblQuerierIPAddress:"查询者地址",

  titEditMcastVlan:"编辑VLAN设置",
  lblOperStatus:"状态",
  lblMRouterPortsAutoLearn:"路由端口自动学习",
  lblQueryRobustness:"查询健壮性",
  lblOperationalQueryRobustness:"查询健壮性",
  lblQueryInterval:"查询间隔",
  lblOperationalQueryInterval:"查询间隔",
  lblQueryMaxResponseInterval:"查询最大响应间隔",
  lblOperationalQueryMaxResponseInterval:"查询最大响应间隔",
  lblLastMemberQueryCounter:"最后一个成员查询计数器",
  lblOperationalLastMemberQueryCounter:"最后一个成员查询计数器",
  lblLastMemberQueryInterval:"最后一个成员查询间隔",
  lblOperationalLastMemberQueryInterval:"最后一个成员查询间隔",
  lblImmediateleave:"立即离开",
  lblIGMPQuerierVersion:"版本",
  lblSecArg:"$1(秒)",

  titIGMPStat:"统计信息",
  lblRX:"接收数据包",
  lblTX:"传输数据包",
  lblTotal:"总计",
  lblValid:"有效",
  lblInValid:"无效",
  lblOther:"其他",
  lblLeave:"离开",
  lblReport:"报告",
  lblGenQry:"常规查询",
  lblSpecGryQry:"特殊组查询",
  lblSpecGrySrcQry:"特定于源的组查询",

  errMcastPortSel:"未选择端口",
  errMcastVlanSel:"不选择VLAN",
  lblUnused:"不使用"
},

<!--#ifdef CONFIG_SYS_PROTO_MVR-->
lang_mvr:{
  lblState:"状态",
  txtComp:"兼容",
  txtDyn:"动态",
  lblMVRGroupStart:"组开始",
  lblMVRGroupSeq:"组数",
  lblMVRQryTime:"查询时间",
  lblMVRMode:"模式",
  lblOperationalGroupNum:"操作组",
  lblMaxGroupNum:"最大值",
  lblCurGroupNum:"当前",

  lblGroupTable:"组地址表",
  lblGroupAddress:"组地址",
  txtPortTable:"端口设置表",
  txtEditPortTable:"编辑端口设置",
  lblPortType:"角色",
  lblPortFastLeave:"立即离开",
  lblNone:"无",
  lblReceiver:"接收器",
  lblSource:"源",

  lblUnused:"不使用"
},
<!--#endif-->

/* Mirror */
<!--#ifdef CONFIG_SYS_MIRROR-->
lang_mirror:{
  titMirrorSettingTbl:"镜像表",
  titEditMirroring:"编辑镜像",
  lblMirrorSessionId:"会话ID",
  lblMirrorDestPort:"监视器端口",
  lblMirrorIngressStateLabel:"发送或接收普通数据包",
  lblMirrorIngressState:"(普通*)",
  lblMirrorIngressStateHint:"\"*\"允许监视器端口发送或接收普通数据包",
  lblMirrorSourceRXPort:"入口",
  lblMirrorSourceTXPort:"出口"
},
<!--#endif-->
lang_alarm:{
	lblState:"告警设置",
	lblRelay:"继电器常开设置",
	titRelaySettingTable:"电源告警设置",
	lblEntryNo1:"电源 1",
	lblEntryNo2:"电源 2",
	lblRelayState:"告警状态",
	lblRelaystatus:"电源状态:",
	txtOk:"正常",
	txtFault:"故障",
	titPortSettingTable:"端口告警设置",
	lblPortstatus:"连接状态",
	txtlink:"已连接",
	txtdown:"未连接"
},
/* Port */
lang_port:{
  titPortSettingTable:"端口设置表",
  titEditPortSetting:"编辑端口设置",
  lblEntryNo:"条目",
  lblPort:"端口",
  lblPortType:"类型",
  lblDescription:"描述",
  lblAdminStatus:"状态",
  lblOperStatus:"链接状态",
  lblSpeed:"速度",
  lblDuplex:"双工",
  lblFlowCtrl:"流控",
  lblFlowCtrlOn:"On",
  lblFlowCtrlOff:"Off",
  lblAuto:"自动",
  lblAutoCapArg:"自动 - $1",
  txtUp:"Up",
  txtDown:"Down",
  txtDuplexFull:"Full",
  txtDuplexHalf:"Half",
  txtMediaCopper:"$1M Copper",
  txtMediaFiber:"$1M Fiber",
  txtMediaGFiber:"$1G Fiber",
  txtMediaGCopper:"$1G Copper",
  txtMediaComboC:"$1M Combo Copper",
  txtMediaComboF:"$1M Combo Fiber",
  <!--#ifdef CONFIG_SYS_PORT_ERR_DISABLED-->
  lblRecoveryInterval:"恢复间隔",
  lblACL:"ACL",
  lblARPRateLimit:"ARP速率限制",
  lblBPDUGuard:"BPDU保护",
  lblBcastFlood:"广播泛洪",
  lblDHCPRateLimit:"DHCP速率限制",
  lblPortSecurity:"端口安全",
  lblSelfLoop:"自循环",
  lblUdld:"UDLD",
  lblUnicastFlood:"单播泛洪",
  lblUnknownMcastFlood:"未知多播泛洪",
  <!--#endif-->
  lblJumboSize:"巨型帧",
  <!--#ifdef CONFIG_SYS_EEE-->
  titEEESettingTable:"EEE设置表",
  titEditEEESetting:"编辑EEE设置",
  lblEEEAdminState:"状态",
  lblEEEState:"运行状态",
  <!--#endif-->
  <!--#ifdef CONFIG_SYS_PORT_SECURITY-->
  titPortSecuritySettingTable:"端口安全表",
  titEditPortSecurity:"编辑端口安全性",
  lblPortSecurityGlobalState:"状态",
  lblPortSecurityState:"状态",
  lblMaxL2Entry:"MAC地址",
  lblViolateAction:"动作",
  <!--#endif-->
  <!--#ifdef CONFIG_SYS_PORT_ERR_DISABLED-->
  titPortErrorDisabledTable:"错误已禁用表",
  lblErrorDisableReason:"原因",
  lblReasonBpduGuard:"BPDU Guard",
  lblReasonUdld:"UDLD",
  lblReasonSelfLoop:"自环",
  lblReasonBroadcastFlood:"广播泛洪",
  lblReasonUnknownMltiCastFlood:"未知的多播泛洪",
  lblReasonUnicastFlood:"单播泛洪",
  lblReasonAcl:"ACL",
  lblReasonPortSecurity:"端口安全",
  lblReasonDhcpRateLimit:"DHCP速率限制",
  lblReasonArpRateLimit:"ARP速率限制",
  lblTimeLeft:"剩余时间(秒)",
  <!--#endif-->
  titProtectTable:"端口组",
lbltype:"类型",
  txtIsolation:"隔离",
  txtForwarding:"互通",

	 titFowardTable:"Port Forwarding Table",
  lblFowardTable:"Port Forwarding List",

  titEditProtect:"编辑受保护的端口",
  lblProtectState:"状态",
  lblProtected:"受保护",
  lblUnprotected:"未保护",
 lbltableId:"Group Id",
  lblisolationPorts:"组成员",


  lblIntf:"接口",
  lblEther:"以太",
  lblRmon:"RMON",
  lblAll:"全部",
  lblMibType:"MIB计数器",
  lblTxPercent:"传输 (%)",
  lblRxPercent:"接收 (%)"
},

<!--#ifdef CONFIG_SYS_PORT_SECURITY-->
/* Port Security */
lang_psecure:{
  titSettingTable:"Port Security Table",
  titPsecureMacTable:"Port Security Address Table",
  titPsecureMacAdd:"Add Port Security Address",
  titPsecureMacEdit:"Edit Port Security Address",
  titEditPsecure:"Edit Port Security",
  lblState:"State",
  lblRateLimit:"Rate Limit",
  lblPps:"Packet / Sec",
  lblAddrLimit:"Address Limit",
  lblViolateAction:"Violate Action",
  lblViolateProtect:"Protect",
  lblViolateRestrict:"Restrict",
  lblViolateShutdown:"Shutdown",
  lblSticky:"Sticky",
  lblTotalAddr:"Total",
  lblConfigAddr:"Configured",
  lblViolateNum:"Violate Number"
},
<!--#endif-->
lang_poe:{
  btnPortRestart:"端口重启",
  btnPortRestore:"恢复缺省",

  lblPoESetting:"PoE设置",
  lblPoESelectedPorts:"选中端口列表",
  lblPoEAdminSatus:"PoE管理状态",
  lblPoEWatchDog:"PoE Watchdog",
  lblPoEProtoType:"PSE 类型",
  lblPoETotalV:"PoE电压(V)",
  lblPoETotalP:"总电源功率(W)",
  lblPoEPowerConsum:"负载总功率(W)",
  lblPoEPowerUsage:"使用功率百分比(%)",

  titPoESelectAll:"全选",
  titPoEAdminStatus:"管理状态",
  titPoEOperation:"Operation",
  titPoEPSEType:"PSE 类型",
  titPoEClass:"Class",
  titPoEMaxP:"最大功率(V)",
  titPoECurrent:"电流(A)",
  titPoEV:"电压(V)",
  titPoEP:"功率(W)"
},

/* QoS */
lang_qos:{
  lblQosMode:"状态",
  lblTrustType:"信任模式",
  lblBasic:"基本",
  titQosPortSettingTable:"端口设置表",
  titQosEditPortSetting:"编辑端口设置",
  lblCoS:"CoS",
  lblCosDscp:"CoS-DSCP",
  lblTrustState:"信任",
  lblRemark:"正在标记",
  lblRemarkCoS:"CoS",
  lblRemarkDSCP:"DSCP",
  lblRemarkIPP:"IP优先级",

  titQueueTable:"队列调度表",
  lblQueue:"队列",
  lblScheduleMethod:"方法",
  lblStrictPriority:"严格优先级",
  lblWrr:"WRR",
  lblWrrWeight:"权重",
  lblWrrBandwidthPercent:"WRR带宽 (%)",

  titCos2QueueMap:"CoS到队列的映射",
  titQueue2CosMap:"队列到CoS映射",

  titDscp2QueueMap:"DSCP到队列的映射",
  titQueue2DscpMap:"队列到DSCP映射",
  lblDSCP:"DSCP",

  titIpp2QueueMap:"队列的IP优先级",
  titQueue2IppMap:"队列到IP优先级映射",
  lblIpp:"IP优先级",

  titBwCtrlTable:"入口/出口端口表",
  titEditBwCtrl:"编辑入口/出口",
  lblIgr:"入口",
  lblEgr:"出口",
  lblState:"状态",
  lblRate:"速率 (Kbps)",

  titEgrQueBwCtrlTable:"出口队列表",
  titEditEgrBwQueCtrl:"编辑出口队列",
  lblQueueNumArg:"队列$1",
  lblCIR:"CIR (Kbps)"
},

<!--#ifdef CONFIG_SYS_LIB_RADIUS-->
lang_radius:{
  lblUseDfltParam:"使用默认参数",
  lblRetries:"重试",
  lblTimeout:"超时",
  lblDeadTime:"死时间",
  lblKeyStr:"密钥字符串",
  lblKeyStrEncrypt:"密钥字符串(已加密)",
  
  titRadiusSrv:"RADIUS表",
  lblPri:"优先级",
  lblUsgType:"用法",
  lblTypeLogin:"登录",
  lblTypeDot1x:"802.1X",
  lblTypeAll:"全部",

  titRadiusSrvAdd:"添加RADIUS服务器",
  titRadiusSrvEdit:"编辑RADIUS服务器",
  lblUseDflt:"使用默认值"
},
<!--#endif-->

<!--#ifdef CONFIG_SYS_MIB_RMON_MGMT_UI-->
lang_rmon:{
  /* RMON Statistic */
  /* Per Port */
  lblBytesRec:"已接收字节",
  lblDropEvents:"丢弃事件",
  lblPktsRec:"已收到数据包",
  lblBPktsRec:"接收到广播数据包",
  lblMPktsRec:"接收到组播数据包",
  lblCRCAlignErr:"CRC&对齐错误",
  lblUndersizePkts:"超小数据包",
  lblOversizePkts:"超大数据包",
  lblFragments:"分片",
  lblJabbers:"Jabbers",
  lblCollisions:"碰撞",
  lblFrames64B:"64字节的帧",
  lblFrames65127B:"65到127字节的帧",
  lblFrames128255B:"128到255字节的帧",
  lblFrames256511B:"256到511字节的帧",
  lblFrames5121023B:"512到1023字节的帧",
  lblFramesOver1024B:"大于1024字节的帧",

  /*  All Port */
  txtRmonStatisticsTable:"统计信息表",
  txtRmonStatisticsIntf:"查看端口统计信息",
  thBytesRec:"已接收字节数",
  thDropEvents:"丢弃<br>事件",
  thPktsRec:"已收到数据包",
  thBPktsRec:"收到的广播数据包",
  thMPktsRec:"已收到多播数据包",
  thCRCAlignErr:"CRC & 对齐<br>错误",
  thUndersizePkts:"超小<br>数据包",
  thOversizePkts:"超大<br>数据包",
  thFragments:"分片",
  thJabbers:"Jabbers",
  thCollisions:"冲突",
  thFrames64B:"帧<br>64字节",
  thFrames65127B:"帧<br>65到127字节",
  thFrames128255B:"帧<br>128到255字节",
  thFrames256511B:"帧<br>256到511字节",
  thFrames5121023B:"帧<br>512到1023字节",
  thFramesOver1024B:"更大帧<br>超过1024字节",

  btnStatsIntfView:"查看",
  msgConfirmClearCounter:"此操作将清除所选接口的接口统计信息,类似以太网的统计信息和RMON统计信息.",

  /* History */
  /* Control Table */
  txtView:"查看",
  txtHistoryControlTable:"历史表",
  txtHistoryLogTable:"查看历史记录",
  thHisIdxBR:"条目",
  thSrcInf:"端口",
  thOwner:"所有者",
  thBuckets:"样本",
  thReqBuckets:"最大",
  thCurrentBuckets:"当前",

  /* Add/Edit Dialog */
  titAddHistory:"添加历史记录",
  titEditHistory:"编辑历史记录",
  lblNewHisIdx:"条目",
  lblEditHisIdx:"条目",
  lblSrcIntf:"端口",
  lblReqBuckets:"最大样本",
  lblInterval:"采样间隔",
  lblOwner:"所有者",

  /* History Table */
  txtHisIdx:"条目",
  thOwner:"所有者",
  thSampleNum:"样品编号",
  thDropEvents:"丢弃<br>事件",
  thBytesRec:"已接收<br>字节数",
  thPktssRec:"已收到<br>数据包",
  thBPktsRec:"广播<br>数据包",
  thMPktsRec:"多播<br>数据包",
  thCRCAlignErr:"CRC & 排列<br>错误",
  thUndersizePkts:"超小<br>数据包",
  thOversizePkts:"超大<br>数据包",
  thFragments:"分片",
  thJabbers:"Jabbers",
  thCollisions:"冲突",
  thUtilization:"利用率",

  /* Event */
  /* Control Table */
  txtEventControlTable:"事件表",
  txtEventLogTable:"查看事件日志",
  thEventIdx:"条目",
  thCommunity:"Community",
  thDescription:"描述",
  thNotifiType:"通知",
  thTime:"时间",
  thOwner:"所有者",

  /* Add/Edit Dialog */
  titAddEvent:"添加事件",
  titEditEvent:"编辑事件",
  lblNewEventIdx:"条目",
  lblEditEventIdx:"条目",
  lblCommunity:"Community",
  lblDescription:"描述",
  lblNotifiType:"通知",
  lblNotifiTypeNone:"无",
  lblNotifiTypeLog:"事件日志",
  lblNotifiTypeTrap:"Trap",
  lblNotifiTypeLogTrap:"事件日志和Trap",
  lblOwner:"所有者",

  /* Event Table */
  thLogNum:"日志ID",
  thLogTime:"时间",
  thDescription:"描述",

  /* RMON Alarem */
  /* Control Table */
  txtAlarmControlTable:"警报表",
  thAlarmIdx:"条目",
  thIntf:"端口",
  thAlarmCnt:"计数器",
  thCntName:"名称",
  thCntValue:"值",
  thSampleType:"采样",
  thAlarmRising:"上升",
  thAlarmFalling:"下降",
  thAlarmThreshold:"阈值",
  thAlarmEvent:"事件",
  thStartupAlarm:"触发器",
  thInterval:"间隔",
  thOwner:"所有者",

  /* Add/Edit Dialog */
  titAddAlarm:"添加警报",
  titEditAlarm:"编辑警报",
  lblNewAlarmIdx:"条目",
  lblEditAlarmIdx:"条目",
  lblIntf:"端口",
  lblCntName:"计数器",
  lblCntValue:"值",
  lblSampleType:"采样",
  lblNone:"无",
  lblAbsolute:"绝对",
  lblDelta:"Delta",
  lblStartupAlarm:"触发器",
  lblRising:"上升",
  lblFalling:"下降",
  lblRisingAndFalling:"上升与下降",
  lblInterval:"间隔",
  lblOwner:"所有者",

  lblBytesRec:"接收的字节(八位字节)",
  lblDropEvents:"丢弃事件",
  lblPktsRec:"收到的数据包",
  lblBPktsRec:"接收到广播数据包",
  lblMPktsRec:"接收到组播数据包",
  lblCRCAlignErr:"CRC&对齐错误",
  lblUndersizePkts:"超小数据包",
  lblOversizePkts:"超大数据包",
  lblFragments:"分片",
  lblJabbers:"Jabbers",
  lblCollisions:"冲突",
  lblFrames64B:"64字节的帧",
  lblFrames65127B:"65到127字节的帧",
  lblFrames128255B:"128到255字节的帧",
  lblFrames256511B:"256到511字节的帧",
  lblFrames5121023B:"512到1023字节的帧",
  lblFramesOver1024B:"大于1024字节的帧",
  txtRmonSnmpDisabledInfo:"当前SNMP服务已禁用.<br>为使RMON配置生效,必须启用$1 SNMP服务$2",
  txtRmonEventDisabledInfo:"对于RMON报警配置,必须添加$1 RMON事件$2",

  /* error message */
  errHistoryTableOverflow:"RMON历史表已满",
  errAlarmTableOverflow:"RMON警报表已满",
  errEventTableOverflow:"RMON事件表已满"
},
<!--#endif-->

<!--#ifdef CONFIG_SYS_L3_ROUTE-->
lang_ipconf:{
  titAddIPv4Intf:"添加 IPv4 接口",
  titEditIPv4Intf:"编辑 IPv4 接口",
  titAddIPv6Intf:"添加 IPv6 接口",
  titEditIPv6Intf:"编辑 IPv6 接口",
  titAddIPv4Route:"添加 IPv4 静态路由",
  titEditIPv4Route:"编辑 IPv4 静态路由",
  titAddIPv6Route:"添加 IPv6 静态路由",
  titEditIPv6Route:"编辑 IPv6 静态路由",
  titAddIPv4Arp:"添加 ARP",
  titEditIPv4Arp:"编辑 ARP",
  titAddIPv6Neigh:"添加 邻居",
  titEditIPv6Neigh:"编辑 邻居",

  lblIPv4IntfTable:"IPv4 接口列表",
  lblIntf:"接口",
  lblIPAddrType:"IP 地址类型",
  lblIPAddr:"IP 地址",
  lblIPv6Addr:"IPv6 地址",
  lblMacAddr:"MAC 地址",
  lblMask:"掩码",
  lblStatus:"状态",
  txtDynamic:"动态",
  txtStatic:"静态",
  txtDHCP:"DHCP",
  txtStatusTentative:"重复地址检测",
  txtStatusValid:"有效的",
  txtStatusValidDuplicated:"有效的但有重复",
  txtStatusDuplicated:"重复的且不能使用",
  txtStatusDelayed:"地址状态延迟",
  txtStatusNotReceived:"地址不存在",

  lblLoopback:"Loopback",
  lblAddressType:"地址类型",
  lblMask:"掩码",
  lblNetworkMask:"网络掩码",
  lblPrefixLength:"前缀长度",

  lblIPv4RouteTable:"IPv4 路由列表",
  lblDstIP:"目标IP",
  lblDstIPPrefix:"目标IP前缀",
  lblRouteType:"路由类型",
  lblNextHopAddr:"下一跳路由IP地址",
  lblRouteOwner:"路由所有者",
  lblMetric:"路径距离",
  lblAdminDistance:"管理距离",
  lblOutIntf:"传出接口",

  txtDefault:"默认",
  txtLocal:"本地",
  txtReject:"目标不可达",
  txtRemote:"远程",
  txtDirectlyConnected:"直接连接",
  txtDHCP:"DHCP",

  lblIPv4ArpTable:"ARP 列表",
  lblArpAgingTime: "ARP 老化时间",
  lblArpClear: "清除ARP表条目",
  lblDynamic:"动态",
  lblStatic:"静态",
  lblNormalAging:"正常老化时间",
  lblStatus:"状态",
  txtIPv4ArpIntf: "注意：只有具有有效IPv4地址的接口可供选择",
  lblV4ArpProxy: "Arp 代理",

  lblIPv6IntfTable:"IPv6 接口列表",
  lblIPv6Routing:"IPv6 单播路由",
  lblDhcpv6Client:"DHCPv6 客户端 ",
  lblStateless:"无状态",
  tblRefresh:"信息<br>刷新时间",
  lblRefresh:"信息刷新时间",
  tblRefreshMin:"最短信息<br>刷新时间",
  lblRefreshMin:"最短信息刷新时间",
  lblAutoConf:"自动配置",
  lblDadAttemps:"防止ARP冲突的尝试次数",
  tblSendICMPUnreachMsg:"发送 ICMPv6<br>不可达",
  lblSendICMPUnreachMsg:"发送ICMPv6不可达",
  lblGlobal:"全球",
  lblLinkLocal:"本地链路",
  lblMcast:"组播地址",
  lblIPv6RouteTable:"IPv6 路由列表",
  lblIPv6Prefix:"IPv6 前缀",
  lblIPv6PrefixLen:"IPv6 前缀长度",
  lblNextHopType:"下一跳类型",

  lblIPv6AddrTable:"IPv6 地址列表",
  lblIPv6AddrType:"IPv6 地址类型",
  lblIPv6Addr:"IPv6 地址",
  lblDADStatus:"DAD 状态",
  lblTentative:"重复地址检测",
  lblDuplicate:"已经检测到重复",
  lblActive:"活动的",
  lblEUI64:"EUI-64",

  lblIPv6NeighTable:"IPv6 邻居列表",
  lblNeighClear: "清除邻居列表",
  lblIPv6Router:"路由"

},
<!--#endif-->
<!--#ifdef CONFIG_SYS_UI_SNMP-->
/*SNMP*/
lang_snmp:{

  <!--#ifdef CONFIG_SYS_SNMPV3-->
  titSnmpViewTable:"查看表",
  titAddSnmpView:"添加视图",
  lblViewName:"视图",
  lblObjectIDSubtree:"OID子树",
  lblObjectIDSubtreeView:"类型”",
  lblIncluded:"包含",
  lblExcluded:"已排除",

  titSnmpGroupTable:"组表",
  titAddSnmpGroup:"添加组",
  titEditSnmpGroup:"编辑组",
  lblGroupName:"组",
  lblSecurityModel:"版本",
  lblSecurityLevel:"安全级别",
  lblNoAuth:"无安全性",
  lblAuth:"身份验证",
  lblPriv:"身份验证和隐私",
  lblView:"查看",
  lblRead:"读取",
  lblWrite:"写",
  lblNotify:"通知",
  lblSNMPv3:"SNMPv3",
  lblNoAuthNoPriv:"无身份验证,无隐私",
  lblAuthNoPriv:"身份验证且没有隐私",
  lblAuthPriv:"身份验证和隐私",

  lblcommType:"类型",
  lblBasic:"基本",
  lblAdvanced:"高级",

  titSnmpUserTable:"用户表",
  titAddSnmpUser:"添加用户",
  titEditSnmpUser:"编辑用户",
  lblUserName:"用户",
  lblAuthTitle:"身份验证",
  lblAuthProt:"方法",
  lblAuthPswd:"密码",
  lblEncryTitle:"隐私",
  lblEncryProt:"方法",
  lblEncryPswd:"密码",
  lblMD5:"MD5",
  lblSHA:"SHA",
  lblDES:"DES",
  lblNone:"无",

  lbllocalEngineID:"本地Engine ID",
  lblEngineID:"Engine ID",
  titRemtEngineID:"远程Engine ID表",
  titAddRemtEngineID:"添加远程Engine ID",
  titEditRemtEngineID:"编辑远程Engine ID",

  lblSnmpSecName:"Community/用户",
  lblTimeout:"超时",
  lblRetries:"重试",
  lblUseDflt:"使用默认值",

  titEditSnmpCommunity:"编辑Community",

  txtGrpNeedViewInfo:"配置$1 SNMP视图$2以将非默认视图与组相关联.",
  txtComNeedGrpInfo:"社区的访问权限由组在高级模式下定义.<br>配置$1 SNMP组$2以将组与社区相关联.",
  txtUserNeedGrpInfo:"配置$1 SNMP组$2以将SNMPv3组与SNMPv3用户相关联.",
  txtNotifyNeedSecInfo:"对于SNMPv1,2通知,需要定义$1 SNMP社区$2.<br>对于SNMPv3通知,必须创建$3 SNMP用户$4.",

  errMIBOIDNotValid:"MIB OID无效",
  errUserAuthPwLenMin:"认证密码长度必须等于或大于8",
  errUserPrivPwLenMin:"隐私密码长度必须等于或大于8",
  errNotEngineID:"值是非法的Engine ID",
  errComNoGrp:"community没有要使用的SNMPv1,2组",
  errUserNoGrp:"用户没有要使用的SNMPv3组",
  errNotifyNoUser:"SNMPv3通知没有要使用的用户",
  <!--#endif-->

  txtNotifyNeedComInfo:"对于SNMPv1,2通知,需要定义$1 SNMP Community $2.",
  errNotifyNoCom:"通知不使用任何community",

  titSnmpCommunityTable:"Community表",
  titAddSnmpCommunity:"添加Community",
  lblCommunityName:"Community",
  lblSNMPv1:"SNMPv1",
  lblSNMPv2:"SNMPv2",
  lblAccess:"访问",
  lblReadOnly:"只读",
  lblReadWrite:"读写",

  lblAuthFail:"身份验证失败",
  lblLinkUpDown:"Link Up / Down",
  lblColdStart:"冷启动",
  lblWarmStart:"热启动",

  titSnmpNotifyTable:"通知表",
  titAddSnmpNotify:"添加通知",
  titEditSnmpNotify:"编辑通知",
  lblNotifyType:"类型",
  lblTraps:"陷阱",
  lblInforms:"通知",
  lblSnmpVer:"版本"
},
<!--#endif-->

<!--#ifdef CONFIG_SYS_STORM_CTRL-->
/* Storm Control */
lang_storm:{
  lblUnit:"模式",
  lblpps:"数据包/秒",
  lblbps:"Kbits / Sec",
  txtpps:"pps",
  txtbps:"Kbps",
  lblIFG:"IFG",
  txtExclude:"排除",
  txtInclude:"包含",
  titStormPortSettingTable:"端口设置表",
  titStormEditPortSetting:"编辑端口设置",
  lblState:"状态",
  lblRate:"速率",
  lblBroadcast:"广播",
  lblUnknownMul:"未知组播",
  lblUnknownUni:"未知单播",
  lblAction:"动作",
  txtDrop:"丢弃",
  txtShutdown:"关闭"
},
<!--#endif-->

<!--#ifdef CONFIG_SYS_PROTO_STP-->
/* Spanning Tree */
lang_stp:{
  lblTrue:"真",
  lblFalse:"假",
  lblState:"状态",
  lblOperMode:"操作模式",
  lblPathCost:"路径成本",
  lblBpduFwd:"BPDU处理",
  lblPriority:"优先级",
  lblHelloTime:"Hello Time",
  lblMaxAge:"最大 Age",
  lblFwdDelay:"转发延迟",
  lblTxHoldCnt:"发送保留计数",
  lblBridgeId:"网桥标识符",
  lblRootBridgeId:"指定的根网桥",
  lblRootPort:"根端口",
  lblRootCost:"根路径成本",
  lblRegionRootBridge:"域根桥",
  lblInternalRootCost:"内部路径成本",
  lblRemainingHop:"剩余跃点",
  lblTcCnt:"拓扑更改计数",
  lblTcLastTime:"最新拓扑更改",
  msgStpModeChange:"更改STP模式可能会导致连接中断.<br>是否要继续?",

  lblPortAdminStatus:"状态",
  lblPortPathCost:"路径成本",
  lblPortPriority:"优先级",
  lblPortEdge:"边缘端口",
  lblPortEdgeOper:"操作边缘",
  lblPortBpduFilter:"BPDU 过滤",
  lblPortBpduGuard:"BPDU保护",
  lblPortP2P:"点对点",
  lblPortP2POper:"操作点对点",
  lblPortMode:"模式",
  lblPortType:"类型",
  lblPortRole:"端口角色",
  lblPortState:"端口状态",
  lblPortDesignatedBridge:"指定网桥",
  lblPortDesignatedPortId:"指定端口ID",
  lblPortDesignatedCost:"指定成本",

  lblRxCnt:"接收BPDU",
  lblTxCnt:"传输BPDU",
  lblConfigBpdu:"配置",
  lblTcnBpdu:"TCN",

  txtSTP: "STP",
  txtRSTP: "RSTP",
  txtOperModeSTP: "STP",
  txtOperModeRSTP: "RSTP",
  txtPathCostLong:"长",
  txtPathCostShort:"短",
  txtBpduFwdFiltering:"过滤",
  txtBpduFwdFlooding:"泛洪",
  txtDayHrMinSecArg:"$1D/$2H/$3M/$4S",

  txtStpIntfStats:"STP端口统计信息",
  txtStpIntfSettingTable:"端口设置表",
  txtStpIntfStatsTable:"统计信息表",

  titStpIntfEdit:"编辑端口设置",

  txtMaster:"Master",
  txtRoot:"根",
  txtDesignated:"指定",
  txtAlternate:"备用",
  txtBackup:"备份",
  txtDisabled:"已禁用",
  txtBlocking:"阻止",
  txtListening:"监听",
  txtDiscarding:"丢弃",
  txtLearning:"学习",
  txtForwarding:"转发",

  btnProtocolMigration:"协议迁移检查",
  btnStatsIntfView:"查看",

  errInvalidPriority:"优先级应该在$1和$2之间，以$3为步长.",

<!--#ifdef CONFIG_SYS_PROTO_STP_MSTP-->
  txtMSTP: "MSTP",
  txtOperModeMSTP: "MSTP",

  lblRegionName:"区域名称",
  lblRevision:"版本",
  lblMaxHop:"最大跳数",
  lblMsti:"MSTI",
  lblMstpBpdu:"MSTP",

  titStpMstiEdit:"编辑MST实例设置",
  titStpMstiIntfEdit:"编辑MST端口设置",

  txtMstiTable:"MST实例表",
  txtMstIntfSettingTable:"MST端口设置表",
  txtInternal:"内部",
  txtBoundary:"边界",
<!--#endif-->

  txtEnd:"结束"
},
<!--#endif-->

/* System */
lang_sys:{
  sirivision_1 :"Copyright &copy; 2001 - 2021 深圳市三旺通信股份有限公司",
	lblBindUsernameStatus:"云端绑定状态",
  lblBindUsername:"用户",
  lblBindCode:"验证码",
  lblBindExpiry:"剩余时间",
  titHome:"智能交换机",
  lblSysinfo:"系统信息",
  titEditSysinfo:"编辑系统信息",
  lblModel:"机型",
  lblSysName:"系统名称",
  lblSysLocation:"地理位置",
  lblSysContact:"联系方式",
  lblMacAddress:"MAC地址",
  lblLoaderVer:"Loader版本",
  lblLoaderDate:"Loader日期",
  lblFwVer:"固件版本",
  lblFwDate:"固件日期",
  lblSysObjID:"OID",
  lblSysUpTime:"启动时间",
  lblSysCurrTime:"现在时间",
  txtSysUptimeArg:"$1 day, $2 hr, $3 min and $4 sec",
  lblTime:"Time",

  lblNetworkIPv4:"IPv4地址",
  lblNetworkIPv4_2:"IPv4地址2",
  lblNetworkIPv6:"IPv6地址",
  lblIPAddressType:"地址类型",
  lblDynamic:"动态",
  lblStatic:"静态",
  lblIPAddress:"IP地址",
  lblMask:"子网掩码",
  lblAdminGateway:"默认网关",
  lblDnsArg:"DNS服务器$1",
  lblIPv4Addr:"IPv4地址",
  lblIPv4Gateway:"IPv4默认网关",
  lblNetworkVLANIPv4:"VLAN IPv4地址",
  lblPrefixLength:"前缀长度",
  lblIPv6AddrAutoConfig:"自动配置",
  lblDHCPv6Client:"DHCPv6客户端",
  lblIPv6Addr:"IPv6地址",
  lblIPv6Gateway:"IPv6网关",
  lblIPv6DefaultGateway:"IPv6默认网关",
  lblLinkLocalAddress:"链接本地地址",
  lblIPv6InUseAddress:"正在使用的IPv6地址",
  lblIPv6InUseGateway:"IPv6网关正在使用",
  lblStateless:"无状态",
  lblInfoRefreshTime:"信息刷新时间",
  lblMinInfoRefreshTime:"最小信息刷新时间",
  lblInfinite:"无限",

  titUserAccountTable:"用户帐户",
  titAddUserAccount:"添加用户帐户",
  titEditUserAccount:"编辑用户帐户",
  lblUserName:"用户名",
  lblPwd:"密码",
  lblPwdConfirm:"确认密码",
  lblPwdEncrypt:"已加密",
  lblPwdText:"清除文字",
  lblPwdNone:"无密码",
  lblPriv:"权限",
  lblPrivTypeAdmin:"管理员",
  lblPrivTypeUser:"用户",
  lblPrivTypeOther:"其他",
  errConfirmPassword:"密码和确认密码字段必须相同",
  errInvalidASCII:"密码是无效的ASCII字符",
  errUserExist:"条目已存在",
  errUserNotExist:"该用户不存在",
  errMaxNumUserArg:"支持的最大本地用户数量为$1",
  errDeleteDeafultUser:"无法删除默认用户名",

  lblSave:"保存",
  lblLogout:"注销",
  msgConfirmSave:"将正在运行的配置保存为启动配置.是否要继续？",
  msgConfirmReboot:"重新启动系统,配置中未保存的更改将丢失.是否要继续?",
  msgConfirmLogout:"注销将断开您当前的会话.您要继续吗?",
  msgRebooting:"系统正在重新启动...",
  msgSaveFail:"保存失败",

  btnReboot:"重新启动",
  btnRestore:"恢复出厂默认设置",
  msgConfirmRestore:"恢复为出厂默认设置.您需要重新启动设备才能生效.是否要继续?",
  msgConfirmRestoreReboot:"立即重新启动设备以使其生效.是否要继续?"
},

<!--#ifdef CONFIG_SYS_LIB_TACPLUS-->
lang_tacplus:{
  lblUseDfltParam:"使用默认参数",
  lblTimeout:"超时",
  lblKeyStr:"密钥字符串",
  lblKeyStrEncrypt:"密钥字符串(已加密)",
  titTacplusSrv:"TACACS +表",
  lblPri:"优先级",
  titTacplusSrvAdd:"添加TACACS +服务器",
  titTacplusSrvEdit:"编辑TACACS +服务器",
  lblUseDflt:"使用默认值"
},
<!--#endif-->

lang_time:{
  lbltimeSrc:"源",
  lbltimeSntp:"SNTP",
  lblSntpServerPort:"服务器端口",
  lbltimeHost:"来自计算机",
  lbltimeManual:"手动时间",
  lbltimeTZ:"时区",
  lbltimeType:"类型",
  lbltimeDST:"夏令时",
  lbltimeDSO:"偏移",
  lbltimeDSNone:"无",
  lbltimeDSRec:"重复发生",
  lbltimeDSNRec:"非重复",
  lbltimeDSUSA:"美国",
  lbltimeDSEU:"欧洲",
  lbltimeFrom:"从",
  lbltimeTo:"到",
  lbltimeNrecF:"非重复来源",
  lbltimeNrecT:"非重复收件人",
  lbltimeDevice:"当前时间",
  lblDay:"天",
  lblWeek:"周",
  lblMonth:"月",
  lblDate:"日期",
  lblTime:"时间",
  lblSun:"星期日",
  lblMon:"星期一",
  lblTue:"星期二",
  lblWed:"星期三",
  lblThu:"星期四",
  lblFri:"星期五",
  lblSat:"星期六",
  lblFirst:"第一",
  lblLast:"最后",
  lblJan:"1月",
  lblFeb:"2月",
  lblMar:"3月",
  lblApr:"4月",
  lblMay:"5月",
  lblJun:"6月",
  lblJul:"7月",
  lblAug:"8月",
  lblSep:"9月",
  lblOct:"10月",
  lblNov:"11月",
  lblDec:"12月",
  lbltimeState:"State",
  lbltimePortSettingTable:"Port Setting Table",
  lbltimePortEditSetting:"Edit Port Setting",
  errMsgDateFormat:"日期值格式不正确",
  errMsgTimeFormat:"时间值格式不正确",
  errMsgDLSEarlier:"开始日期必须早于结束日期.",
  errMsgDLSGreaterOffset:"夏时制从和到之间的时差必须大于时间设置偏移量"
},

<!--#ifdef CONFIG_SYS_PROTO_UDLD-->
lang_udld:{
  titUdldPortSettingTable:"端口设置表",
  titUdldEditPortSetting:"编辑端口设置",
  titTableUdldNeighbor:"邻居表",
  lblUdldMsgTime:"消息时间",
  lblPortMode:"模式",
  lblUdldPortDisable:"已禁用",
  lblUdldPortNormal:"普通",
  lblUdldPortAggresive:"积极",
  lblUdldBidirectionalState:"双向状态",
  lblUdldOperState:"运行状态",
  lblUdldNeighbors:"邻居",
  lblUdldMsgInterval:"消息<br>间隔",
  lblUdldTimeoutInterval:"超时<br>间隔",
  lblUdldExpirationTime:"到期<br>时间",
  lblUdldcurNeistate:"当前邻居状态",
  lblUdldDeviceID:"设备ID",
  lblUdldDeviceName:"设备名称",
  lblUdldPortID:"端口ID",
  lblUdldBiState_0:"未知",
  lblUdldBiState_1:"发送/接收循环",
  lblUdldBiState_2:"邻居的回显为空",
  lblUdldBiState_3:"已报告与邻居状态不匹配",
  lblUdldBiState_4:"双向",
  lblUdldBiState_5:"单向",
  lblUdldOperState_0:"Link down",
  lblUdldOperState_1:"",
  lblUdldOperState_2:"Link up",
  lblUdldOperState_3:"广告",
  lblUdldOperState_4:"检测",
  lblUdldOperState_5:"扩展检测",
  lblUdldOperState_6:"广告-检测到单个邻居",
  lblUdldOperState_7:"广告-检测到多个邻居",
  lblUdldOperState_8:"禁用的端口",
  lblUdldOperState_9:"Link up"
},
<!--#endif-->

/* VLAN */
lang_vlan:{
  titVLAN:"VLAN表",
  titVLANConfigurationTable:"VLAN配置表",
  titVLANPortSettingTable:"端口设置表",
  titVLANMembershipSettingTable:"成员资格表",
  titVLANEdit:"Edit VLAN",
  titVLANNameEdit:"编辑VLAN名称",
  titVLANPortEdit:"编辑端口设置",
  lblVlanName:"名称",
  lblVlanMode:"模式",
  lblVlanType:"类型",
  lblVlanIntfState:"VLAN Interface State",
  lblVlanMembership:"成员资格",
  lblVlanPVID:"PVID",
  lblVlanForbidden:"禁止",
  lblVlanExcluded:"已排除",
  lblVlanTagged:"已标记",
  lblVlanUntagged:"未标记",
  lblVlanHybrid:"Hybrid",
  lblVlanTrunk:"Trunk",
  lblVlanAccess:"Access",
  lblVlanTunnel:"隧道(Qinq)",
  lblVlanAcceptFrameType:"接受帧类型",
  lblVlanIngressFiltering:"入口过滤",
  lblVlanUplink:"上行",
  lblVlanTPID:"TPID",
  lblVlanAll:"全部",
  lblVlanTagOnly:"仅Tag",
  lblVlanUntagOnly:"仅Untag",
  lblVlanDefault:"默认",
  lblVlanAdmin:"管理VLAN",
  lblVlanOper:"操作VLAN",
  lblCreatedVlans:"创建的VLAN",
  lblManagementVLAN:"管理VLAN",

  errMsgManagementVLAN:"注意:更改管理VLAN可能导致连接中断"
},

<!--#ifdef CONFIG_SYS_MACVLAN-->
/* VLAN Mac */
lang_vlanmac:{
  titMVGroupTable:"MAC组表",
  titMVAddGroup:"添加MAC组",
  titMVEditGroup:"编辑MAC组",
  titMVBindingTable:"组绑定表",
  titMVAddBinding:"添加组绑定",
  titMVEditBinding:"编辑组绑定",
  lblMVMac:"MAC地址",
  lblMVMacMask:"遮罩",
  lblMVGroup:"组ID",
  msgMVHybridPort:"注意:仅VLAN Hybrid端口可以设置MAC VLAN"
},
<!--#endif-->

<!--#ifdef CONFIG_SYS_VOICEVLAN-->
/* VLAN Voice */
lang_vlanvoice:{
  titVVPortSettingTable:"端口设置表",
  titVVEditPortSettingTable:"编辑端口设置",
  titVVOUITable:"语音OUI表",
  titVVOUIAdd:"添加语音OUI",
  titVVOUIEdit:"编辑语音OUI",
  lblVVState:"状态",
  lblVVRemark:"CoS / 802.1p&nbsp<br>重标记",
  lblVVAgingTime:"老化时间",
  lblVVPortState:"状态",
  lblVVPortMode:"模式",
  lblVVPortCosMdoe:"QoS策略",
  lblVVAuto:"自动",
  lblVVManual:"手册",
  lblVVAll:"全部",
  lblVVSource:"语音数据包",
  lblVVOUIAddress:"OUI",
  lblVVDescription:"描述"
},
<!--#endif-->
<!--#ifdef CONFIG_SYS_PROTO_ERPS-->
/* VLAN Voice */
lang_erps:{
  Status:"状态",
  None:"None",
  Ring:"Ring",
  Owner:"RPL Owner",
  port_set:"Port",
  ctl_vlan:"Control Vlan",
  wtr_timer_val:"WTR Timer",
  guard_timer_val:"Guard Timer",
  hld_timer_val:"Holdoff Timer",
  mel:"RAPS MEL",
  erpsPortSettingTable:"端口设置表",
  lblErpsRole:"Port Role",
  lblErpsStatus:"Port Status",
  lblErpsAction:"Action"
  },
<!--#endif-->
<!--#ifdef CONFIG_SYS_PROTO_ERPS-->
/* VLAN Voice */
lang_erps:{
  Status:"状态",
  None:"None",
  Ring:"Ring",
  Owner:"RPL Owner",
  port_set:"Port",
  ctl_vlan:"Control Vlan",
  wtr_timer_val:"WTR Timer",
  guard_timer_val:"Guard Timer",
  hld_timer_val:"Holdoff Timer",
  mel:"RAPS MEL",
  erpsPortSettingTable:"端口设置表",
  lblErpsRole:"Port Role",
  lblErpsStatus:"Port Status",
  lblErpsAction:"Action"
  },
<!--#endif-->
<!--#ifdef CONFIG_SYS_PROTOCOL_VLAN-->
/* VLAN Protocol */
lang_vlanprotocol:{
  titPVGroupTable:"协议组表",
  titPVAddGroup:"添加协议组",
  titPVEditGroup:"编辑协议组",
  titPVBindingTable:"组绑定表",
  titPVAddBinding:"添加组绑定",
  titPVEditBinding:"编辑组绑定",
  lblPVProtocolValue:"协议值",
  lblPVFrameType:"帧类型",
  lblPVGroup:"组ID",
  lblPVEII:"Ethernet_II",
  lblPVLLC:"IEEE802.3_LLC_Other",
  lblPVSNAP:"RFC_1042",
  msgPVHybridPort:"注意:仅VLAN Hybrid端口可以设置协议VLAN"
},
<!--#endif-->

<!--#ifdef CONFIG_SYS_SURVEILLANCEVLAN-->
/* Surveillance Voice */
lang_vlansurveillance:{
  titSVPortSettingTable:"端口设置表",
  titSVEditPortSettingTable:"编辑端口设置",
  titSVOUITable:"监视OUI表",
  titSVOUIAdd:"添加监视OUI",
  titSVOUIEdit:"编辑监视OUI",
  lblSVState:"状态",
  lblSVRemark:"CoS / 802.1p&nbsp<br>重标记",
  lblSVAgingTime:"老化时间",
  lblSVPortState:"状态",
  lblSVPortMode:"模式",
  lblSVPortCosMdoe:"QoS策略",
  lblSVAuto:"自动",
  lblSVManual:"手册",
  lblSVAll:"全部",
  lblSVSource:"视频数据包",
  lblSVOUIAddress:"OUI",
  lblSVDescription:"描述"
},
<!--#endif-->

lang_zzz:{
  dummy:""
}
};


var ready_js_defLang = 1;
